import type {
  MediaConnection,
  CampaignPerformance,
  OrganicContentPerformance,
  AIInsight,
  SmartAlert,
  ExecutiveReport,
  AIGenerationLog,
  KPIWithStatus,
} from './brand-types'

// Media Connections Mock Data
export const mockMediaConnections: MediaConnection[] = [
  {
    id: 'mc1',
    brandId: 'brand1',
    type: 'meta_ads',
    name: 'Meta Ads',
    status: 'connected',
    accountId: 'act_123456789',
    accountName: 'Residencial Bosques - Ads',
    lastSync: '2024-04-15T10:30:00Z',
    metrics: ['impressions', 'reach', 'clicks', 'leads', 'conversions', 'spend'],
    permissions: ['ads_read', 'ads_management', 'insights'],
    connectedAt: '2024-01-15T08:00:00Z',
  },
  {
    id: 'mc2',
    brandId: 'brand1',
    type: 'google_ads',
    name: 'Google Ads',
    status: 'connected',
    accountId: '123-456-7890',
    accountName: 'Bosques Premium',
    lastSync: '2024-04-15T10:25:00Z',
    metrics: ['impressions', 'clicks', 'conversions', 'cost'],
    permissions: ['readonly'],
    connectedAt: '2024-02-01T09:00:00Z',
  },
  {
    id: 'mc3',
    brandId: 'brand1',
    type: 'instagram',
    name: 'Instagram',
    status: 'connected',
    accountId: '17841400000000000',
    accountName: '@residencial_bosques',
    lastSync: '2024-04-15T10:35:00Z',
    metrics: ['reach', 'impressions', 'engagement', 'followers', 'profile_views'],
    permissions: ['instagram_basic', 'instagram_content_publish', 'instagram_manage_insights'],
    connectedAt: '2024-01-10T08:00:00Z',
  },
  {
    id: 'mc4',
    brandId: 'brand1',
    type: 'facebook',
    name: 'Facebook',
    status: 'connected',
    accountId: '1234567890',
    accountName: 'Residencial Bosques',
    lastSync: '2024-04-15T10:35:00Z',
    metrics: ['reach', 'impressions', 'engagement', 'page_views', 'messages'],
    permissions: ['pages_read_engagement', 'pages_manage_posts'],
    connectedAt: '2024-01-10T08:00:00Z',
  },
  {
    id: 'mc5',
    brandId: 'brand1',
    type: 'google_analytics',
    name: 'Google Analytics',
    status: 'connected',
    accountId: 'UA-123456789-1',
    accountName: 'Bosques Website',
    lastSync: '2024-04-15T10:40:00Z',
    metrics: ['sessions', 'users', 'pageviews', 'bounce_rate', 'conversions'],
    permissions: ['analytics_readonly'],
    connectedAt: '2024-01-20T10:00:00Z',
  },
  {
    id: 'mc6',
    brandId: 'brand1',
    type: 'tiktok_ads',
    name: 'TikTok Ads',
    status: 'disconnected',
    metrics: [],
    permissions: [],
  },
  {
    id: 'mc7',
    brandId: 'brand1',
    type: 'whatsapp_business',
    name: 'WhatsApp Business',
    status: 'connected',
    accountId: '+52 55 1234 5678',
    accountName: 'Bosques Ventas',
    lastSync: '2024-04-15T10:45:00Z',
    metrics: ['messages_sent', 'messages_received', 'conversations'],
    permissions: ['whatsapp_business_messaging'],
    connectedAt: '2024-03-01T11:00:00Z',
  },
  {
    id: 'mc8',
    brandId: 'brand1',
    type: 'hubspot',
    name: 'HubSpot CRM',
    status: 'error',
    accountId: '12345678',
    accountName: 'Bosques CRM',
    lastSync: '2024-04-10T08:00:00Z',
    metrics: ['contacts', 'deals', 'tasks'],
    permissions: ['crm.objects.contacts.read'],
    errors: ['Token expirado. Por favor reconecta la cuenta.'],
    connectedAt: '2024-02-15T14:00:00Z',
  },
]

// Campaign Performance Mock Data
export const mockCampaignPerformance: CampaignPerformance[] = [
  {
    id: 'cp1',
    brandId: 'brand1',
    campaignId: 'camp_001',
    campaignName: 'Lanzamiento Fase 2 - Leads',
    channel: 'meta_ads',
    objective: 'lead_generation',
    status: 'active',
    investment: 85000,
    impressions: 1250000,
    reach: 450000,
    clicks: 18500,
    ctr: 1.48,
    cpc: 4.59,
    cpm: 68,
    leads: 892,
    cpl: 95.29,
    conversions: 156,
    cpa: 545.45,
    appointments: 78,
    cpAppointment: 1089.74,
    sales: 12,
    revenue: 42000000,
    roas: 494.12,
    frequency: 2.78,
    buyerPersonaId: 'persona1',
    funnelStage: 'conversion',
    startDate: '2024-03-01',
    endDate: '2024-04-30',
    period: 'Marzo-Abril 2024',
  },
  {
    id: 'cp2',
    brandId: 'brand1',
    campaignId: 'camp_002',
    campaignName: 'Branding - Awareness',
    channel: 'meta_ads',
    objective: 'brand_awareness',
    status: 'active',
    investment: 35000,
    impressions: 2100000,
    reach: 780000,
    clicks: 12600,
    ctr: 0.6,
    cpc: 2.78,
    cpm: 16.67,
    leads: 0,
    cpl: 0,
    conversions: 0,
    cpa: 0,
    appointments: 0,
    cpAppointment: 0,
    sales: 0,
    revenue: 0,
    roas: 0,
    frequency: 2.69,
    funnelStage: 'awareness',
    startDate: '2024-03-15',
    period: 'Marzo-Abril 2024',
  },
  {
    id: 'cp3',
    brandId: 'brand1',
    campaignId: 'camp_003',
    campaignName: 'Search - Departamentos CDMX',
    channel: 'google_ads',
    objective: 'conversions',
    status: 'active',
    investment: 65000,
    impressions: 380000,
    reach: 285000,
    clicks: 9500,
    ctr: 2.5,
    cpc: 6.84,
    cpm: 171.05,
    leads: 425,
    cpl: 152.94,
    conversions: 89,
    cpa: 730.34,
    appointments: 45,
    cpAppointment: 1444.44,
    sales: 8,
    revenue: 28000000,
    roas: 430.77,
    frequency: 1.33,
    buyerPersonaId: 'persona2',
    funnelStage: 'conversion',
    startDate: '2024-02-01',
    period: 'Feb-Abril 2024',
  },
  {
    id: 'cp4',
    brandId: 'brand1',
    campaignId: 'camp_004',
    campaignName: 'Retargeting - Visitantes Web',
    channel: 'meta_ads',
    objective: 'conversions',
    status: 'active',
    investment: 25000,
    impressions: 450000,
    reach: 85000,
    clicks: 6750,
    ctr: 1.5,
    cpc: 3.7,
    cpm: 55.56,
    leads: 312,
    cpl: 80.13,
    conversions: 67,
    cpa: 373.13,
    appointments: 34,
    cpAppointment: 735.29,
    sales: 5,
    revenue: 17500000,
    roas: 700,
    frequency: 5.29,
    funnelStage: 'consideration',
    startDate: '2024-03-01',
    period: 'Marzo-Abril 2024',
  },
  {
    id: 'cp5',
    brandId: 'brand1',
    campaignId: 'camp_005',
    campaignName: 'Display - Remarketing',
    channel: 'google_ads',
    objective: 'remarketing',
    status: 'paused',
    investment: 15000,
    impressions: 890000,
    reach: 120000,
    clicks: 3560,
    ctr: 0.4,
    cpc: 4.21,
    cpm: 16.85,
    leads: 89,
    cpl: 168.54,
    conversions: 18,
    cpa: 833.33,
    appointments: 9,
    cpAppointment: 1666.67,
    sales: 1,
    revenue: 3500000,
    roas: 233.33,
    frequency: 7.42,
    funnelStage: 'consideration',
    startDate: '2024-01-15',
    endDate: '2024-03-31',
    period: 'Q1 2024',
  },
  {
    id: 'cp6',
    brandId: 'brand1',
    campaignId: 'camp_006',
    campaignName: 'Lookalike - Compradores Previos',
    channel: 'meta_ads',
    objective: 'lead_generation',
    status: 'active',
    investment: 45000,
    impressions: 680000,
    reach: 320000,
    clicks: 10200,
    ctr: 1.5,
    cpc: 4.41,
    cpm: 66.18,
    leads: 534,
    cpl: 84.27,
    conversions: 98,
    cpa: 459.18,
    appointments: 49,
    cpAppointment: 918.37,
    sales: 7,
    revenue: 24500000,
    roas: 544.44,
    frequency: 2.13,
    buyerPersonaId: 'persona1',
    funnelStage: 'conversion',
    startDate: '2024-03-15',
    period: 'Marzo-Abril 2024',
  },
]

// Organic Content Performance Mock Data
export const mockOrganicPerformance: OrganicContentPerformance[] = [
  {
    id: 'oc1',
    brandId: 'brand1',
    contentId: 'post_001',
    title: 'Tour Virtual Penthouse A1',
    platform: 'instagram',
    type: 'reel',
    pillar: 'producto',
    funnelStage: 'consideration',
    reach: 125000,
    impressions: 185000,
    engagement: 8750,
    engagementRate: 7.0,
    likes: 6200,
    comments: 342,
    shares: 1580,
    saves: 628,
    views: 156000,
    watchTime: 12.5,
    retention: 68,
    leads: 45,
    buyerPersonaId: 'persona1',
    publishedAt: '2024-04-10T14:00:00Z',
  },
  {
    id: 'oc2',
    brandId: 'brand1',
    contentId: 'post_002',
    title: 'Amenidades - Rooftop con vista',
    platform: 'instagram',
    type: 'carrusel',
    pillar: 'lifestyle',
    funnelStage: 'awareness',
    reach: 78000,
    impressions: 112000,
    engagement: 5460,
    engagementRate: 7.0,
    likes: 4200,
    comments: 186,
    shares: 524,
    saves: 550,
    views: 0,
    buyerPersonaId: 'persona2',
    publishedAt: '2024-04-08T18:00:00Z',
  },
  {
    id: 'oc3',
    brandId: 'brand1',
    contentId: 'post_003',
    title: 'Testimonio - Familia González',
    platform: 'instagram',
    type: 'video',
    pillar: 'social_proof',
    funnelStage: 'conversion',
    reach: 45000,
    impressions: 62000,
    engagement: 3100,
    engagementRate: 6.89,
    likes: 2400,
    comments: 245,
    shares: 312,
    saves: 143,
    views: 38000,
    watchTime: 45.2,
    retention: 72,
    leads: 28,
    publishedAt: '2024-04-05T12:00:00Z',
  },
  {
    id: 'oc4',
    brandId: 'brand1',
    contentId: 'post_004',
    title: 'Tips: Cómo elegir tu primer departamento',
    platform: 'instagram',
    type: 'carrusel',
    pillar: 'educativo',
    funnelStage: 'awareness',
    reach: 92000,
    impressions: 134000,
    engagement: 6700,
    engagementRate: 7.28,
    likes: 5100,
    comments: 423,
    shares: 890,
    saves: 287,
    buyerPersonaId: 'persona3',
    publishedAt: '2024-04-03T16:00:00Z',
  },
  {
    id: 'oc5',
    brandId: 'brand1',
    contentId: 'post_005',
    title: 'Behind the Scenes - Construcción',
    platform: 'instagram',
    type: 'story',
    pillar: 'behind_scenes',
    funnelStage: 'consideration',
    reach: 28000,
    impressions: 35000,
    engagement: 1400,
    engagementRate: 5.0,
    likes: 0,
    comments: 0,
    shares: 0,
    saves: 0,
    views: 28000,
    retention: 45,
    publishedAt: '2024-04-12T10:00:00Z',
  },
  {
    id: 'oc6',
    brandId: 'brand1',
    contentId: 'post_006',
    title: 'Promoción Abril - 10% descuento',
    platform: 'facebook',
    type: 'imagen',
    pillar: 'promocional',
    funnelStage: 'conversion',
    reach: 56000,
    impressions: 78000,
    engagement: 2340,
    engagementRate: 4.18,
    likes: 1800,
    comments: 156,
    shares: 284,
    saves: 100,
    clicks: 890,
    leads: 67,
    publishedAt: '2024-04-01T09:00:00Z',
  },
  {
    id: 'oc7',
    brandId: 'brand1',
    contentId: 'post_007',
    title: 'Render 3D - Vista nocturna',
    platform: 'instagram',
    type: 'imagen',
    pillar: 'producto',
    funnelStage: 'awareness',
    reach: 67000,
    impressions: 89000,
    engagement: 4020,
    engagementRate: 6.0,
    likes: 3200,
    comments: 134,
    shares: 456,
    saves: 230,
    publishedAt: '2024-04-11T20:00:00Z',
  },
  {
    id: 'oc8',
    brandId: 'brand1',
    contentId: 'post_008',
    title: 'Live: Q&A con arquitecto',
    platform: 'instagram',
    type: 'live',
    pillar: 'educativo',
    funnelStage: 'consideration',
    reach: 12000,
    impressions: 18000,
    engagement: 2160,
    engagementRate: 18.0,
    likes: 890,
    comments: 1120,
    shares: 150,
    saves: 0,
    views: 8500,
    watchTime: 32.5,
    retention: 28,
    publishedAt: '2024-04-09T19:00:00Z',
  },
]

// AI Insights Mock Data
export const mockAIInsights: AIInsight[] = [
  {
    id: 'ins1',
    brandId: 'brand1',
    type: 'opportunity',
    title: 'Alto engagement en contenido de tours virtuales',
    finding: 'Los Reels de tours virtuales tienen un engagement rate 3.2x mayor que el promedio de la industria.',
    evidence: 'El Reel "Tour Virtual Penthouse A1" alcanzó 7% de engagement vs 2.2% promedio del sector inmobiliario.',
    metric: 'engagement_rate',
    metricValue: 7.0,
    metricChange: 218,
    impact: 'high',
    recommendation: 'Incrementar la producción de tours virtuales en formato Reel a 4 por mes.',
    priority: 1,
    action: 'Crear calendario de producción de tours virtuales',
    actionUrl: '/orbit-marketing-intelligence/brands/brand1/brief',
    dataSource: 'Instagram Insights',
    gemAgent: 'content-analyst',
    createdAt: '2024-04-15T08:00:00Z',
    acknowledged: false,
  },
  {
    id: 'ins2',
    brandId: 'brand1',
    type: 'warning',
    title: 'CPL incrementando en Google Ads',
    finding: 'El costo por lead en Google Ads ha incrementado 23% en las últimas 2 semanas.',
    evidence: 'CPL actual: $152.94 vs objetivo máximo: $150. Tendencia ascendente desde semana 14.',
    metric: 'cpl',
    metricValue: 152.94,
    metricChange: 23,
    impact: 'medium',
    recommendation: 'Revisar keywords negativas y ajustar pujas en campañas de Search.',
    priority: 2,
    action: 'Optimizar campañas de Google Ads',
    actionUrl: '/orbit-marketing-intelligence/campaigns',
    dataSource: 'Google Ads',
    gemAgent: 'campaign-optimizer',
    createdAt: '2024-04-14T10:30:00Z',
    acknowledged: true,
  },
  {
    id: 'ins3',
    brandId: 'brand1',
    type: 'trend',
    title: 'Buyer Persona "Inversionista" con mejor ROI',
    finding: 'Las campañas dirigidas al segmento de inversionistas generan 2.5x más ROAS que otros segmentos.',
    evidence: 'ROAS promedio inversionistas: 544% vs profesionales jóvenes: 217%.',
    metric: 'roas',
    metricValue: 544,
    impact: 'high',
    recommendation: 'Reasignar 20% del presupuesto de awareness hacia campañas de conversión para inversionistas.',
    priority: 1,
    action: 'Ajustar distribución de presupuesto',
    actionUrl: '/orbit-marketing-intelligence/brands/brand1/objectives',
    dataSource: 'Meta Ads + CRM',
    gemAgent: 'budget-optimizer',
    createdAt: '2024-04-13T14:00:00Z',
    acknowledged: false,
  },
  {
    id: 'ins4',
    brandId: 'brand1',
    type: 'pattern',
    title: 'Mejor horario de publicación identificado',
    finding: 'El contenido publicado entre 6-8 PM obtiene 45% más alcance que otros horarios.',
    evidence: 'Análisis de 30 publicaciones. Alcance promedio 6-8 PM: 85,000 vs otros horarios: 58,600.',
    metric: 'reach',
    metricValue: 85000,
    metricChange: 45,
    impact: 'medium',
    recommendation: 'Concentrar publicaciones principales entre 6-8 PM de lunes a viernes.',
    priority: 3,
    action: 'Actualizar calendario de contenido',
    dataSource: 'Instagram Insights',
    gemAgent: 'content-analyst',
    createdAt: '2024-04-12T09:00:00Z',
    acknowledged: true,
  },
  {
    id: 'ins5',
    brandId: 'brand1',
    type: 'anomaly',
    title: 'Caída inusual en tráfico web fin de semana',
    finding: 'El tráfico web del fin de semana pasado fue 35% menor al promedio histórico.',
    evidence: 'Sesiones sábado-domingo: 1,240 vs promedio: 1,908. Sin cambios en campañas.',
    metric: 'sessions',
    metricValue: 1240,
    metricChange: -35,
    impact: 'low',
    recommendation: 'Verificar si hubo problemas técnicos en el sitio o eventos externos que afectaron el tráfico.',
    priority: 4,
    action: 'Revisar Google Analytics y status del sitio',
    actionUrl: '/orbit-marketing-intelligence/brands/brand1/analytics',
    dataSource: 'Google Analytics',
    gemAgent: 'anomaly-detector',
    createdAt: '2024-04-15T06:00:00Z',
    acknowledged: false,
  },
  {
    id: 'ins6',
    brandId: 'brand1',
    type: 'recommendation',
    title: 'Oportunidad de contenido UGC',
    finding: 'Los testimoniales de clientes generan 2.8x más leads que contenido de marca.',
    evidence: 'Video testimonio Familia González: 28 leads vs promedio contenido marca: 10 leads.',
    metric: 'leads',
    metricValue: 28,
    metricChange: 180,
    impact: 'high',
    recommendation: 'Implementar programa de recolección de testimoniales con incentivos para compradores.',
    priority: 2,
    action: 'Diseñar programa de UGC',
    dataSource: 'Content Performance Analysis',
    gemAgent: 'content-strategist',
    createdAt: '2024-04-14T16:00:00Z',
    acknowledged: false,
  },
]

// Smart Alerts Mock Data
export const mockSmartAlerts: SmartAlert[] = [
  {
    id: 'alert1',
    brandId: 'brand1',
    type: 'critical',
    category: 'budget',
    title: 'Presupuesto Meta Ads al 92%',
    description: 'El presupuesto mensual de Meta Ads está cerca de agotarse con 8 días restantes del mes.',
    metric: 'budget_spent',
    threshold: 90,
    currentValue: 92,
    targetValue: 100,
    variance: -8,
    actionUrl: '/orbit-marketing-intelligence/brands/brand1/objectives',
    actionLabel: 'Revisar presupuesto',
    createdAt: '2024-04-22T08:00:00Z',
    acknowledged: false,
  },
  {
    id: 'alert2',
    brandId: 'brand1',
    type: 'attention',
    category: 'kpi',
    title: 'CPL Google Ads fuera de rango',
    description: 'El CPL de Google Ads ($152.94) supera el máximo establecido ($150).',
    metric: 'cpl',
    threshold: 150,
    currentValue: 152.94,
    targetValue: 100,
    variance: 2,
    campaignId: 'camp_003',
    actionUrl: '/orbit-marketing-intelligence/campaigns',
    actionLabel: 'Optimizar campaña',
    createdAt: '2024-04-21T14:30:00Z',
    acknowledged: false,
  },
  {
    id: 'alert3',
    brandId: 'brand1',
    type: 'opportunity',
    category: 'campaign',
    title: 'Campaña Lookalike con alto rendimiento',
    description: 'La campaña de Lookalike está generando leads a $84.27, 16% por debajo del objetivo.',
    metric: 'cpl',
    threshold: 100,
    currentValue: 84.27,
    targetValue: 100,
    variance: -16,
    campaignId: 'camp_006',
    actionUrl: '/orbit-marketing-intelligence/brands/brand1/performance/channels',
    actionLabel: 'Escalar campaña',
    createdAt: '2024-04-20T10:00:00Z',
    acknowledged: true,
  },
  {
    id: 'alert4',
    brandId: 'brand1',
    type: 'info',
    category: 'content',
    title: 'Reel viral detectado',
    description: 'El Reel "Tour Virtual Penthouse A1" superó 100K de alcance en 48 horas.',
    metric: 'reach',
    currentValue: 125000,
    targetValue: 50000,
    variance: 150,
    contentId: 'post_001',
    actionUrl: '/orbit-marketing-intelligence/brands/brand1/rankings/organic',
    actionLabel: 'Ver performance',
    createdAt: '2024-04-12T16:00:00Z',
    acknowledged: true,
  },
  {
    id: 'alert5',
    brandId: 'brand1',
    type: 'risk',
    category: 'system',
    title: 'Error de sincronización HubSpot',
    description: 'La conexión con HubSpot CRM falló. Los datos de leads no se están sincronizando.',
    actionUrl: '/orbit-marketing-intelligence/brands/brand1/media',
    actionLabel: 'Reconectar',
    createdAt: '2024-04-15T09:00:00Z',
    acknowledged: false,
  },
  {
    id: 'alert6',
    brandId: 'brand1',
    type: 'attention',
    category: 'kpi',
    title: 'Frecuencia elevada en Retargeting',
    description: 'La frecuencia de la campaña de Retargeting (5.29) está causando fatiga de audiencia.',
    metric: 'frequency',
    threshold: 4,
    currentValue: 5.29,
    targetValue: 3,
    variance: 32,
    campaignId: 'camp_004',
    actionUrl: '/orbit-marketing-intelligence/campaigns',
    actionLabel: 'Ajustar audiencia',
    createdAt: '2024-04-19T11:00:00Z',
    acknowledged: false,
  },
  {
    id: 'alert7',
    brandId: 'brand1',
    type: 'success',
    category: 'kpi',
    title: 'ROAS objetivo alcanzado',
    description: 'El ROAS general del mes (494%) superó el objetivo establecido (400%).',
    metric: 'roas',
    threshold: 400,
    currentValue: 494,
    targetValue: 400,
    variance: 24,
    createdAt: '2024-04-18T08:00:00Z',
    acknowledged: true,
  },
]

// Executive Report Mock Data
export const mockExecutiveReports: ExecutiveReport[] = [
  {
    id: 'report1',
    brandId: 'brand1',
    month: 3,
    year: 2024,
    period: 'Marzo 2024',
    status: 'approved',
    summary: 'Marzo fue un mes excepcional para Residencial Bosques con un ROAS de 494%, superando el objetivo del 400%. Se generaron 2,163 leads totales con una inversión de $270,000 MXN. Las campañas de Meta Ads lideraron en eficiencia con un CPL de $89.50.',
    highlights: [
      'ROAS récord de 494%, 23% por encima del objetivo',
      'Reducción de CPL en 15% vs mes anterior',
      '12 ventas cerradas por $42M MXN',
      'Campaña de Lookalike con mejor performance histórico',
    ],
    kpis: [
      { name: 'Leads Totales', code: 'leads', value: 2163, target: 2000, variance: 8.15, status: 'above', trend: 'up', previousValue: 1890 },
      { name: 'CPL Promedio', code: 'cpl', value: 95.29, target: 100, variance: -4.71, status: 'above', trend: 'down', previousValue: 112.50 },
      { name: 'ROAS', code: 'roas', value: 494, target: 400, variance: 23.5, status: 'above', trend: 'up', previousValue: 380 },
      { name: 'Citas Generadas', code: 'appointments', value: 215, target: 180, variance: 19.4, status: 'above', trend: 'up', previousValue: 168 },
      { name: 'Ventas', code: 'sales', value: 12, target: 10, variance: 20, status: 'above', trend: 'up', previousValue: 8 },
    ],
    rankings: [
      {
        type: 'campaign',
        items: [
          { id: 'camp_001', name: 'Lanzamiento Fase 2 - Leads', metric: 'leads', value: 892, rank: 1 },
          { id: 'camp_006', name: 'Lookalike - Compradores Previos', metric: 'leads', value: 534, rank: 2 },
          { id: 'camp_003', name: 'Search - Departamentos CDMX', metric: 'leads', value: 425, rank: 3 },
        ]
      },
      {
        type: 'content',
        items: [
          { id: 'post_001', name: 'Tour Virtual Penthouse A1', metric: 'engagement', value: 8750, rank: 1 },
          { id: 'post_004', name: 'Tips: Cómo elegir tu primer depto', metric: 'engagement', value: 6700, rank: 2 },
          { id: 'post_002', name: 'Amenidades - Rooftop', metric: 'engagement', value: 5460, rank: 3 },
        ]
      }
    ],
    topCampaigns: ['Lanzamiento Fase 2 - Leads', 'Lookalike - Compradores Previos'],
    topContent: ['Tour Virtual Penthouse A1', 'Tips: Cómo elegir tu primer departamento'],
    learnings: [
      'Los tours virtuales en formato Reel generan 3x más engagement que imágenes estáticas',
      'El segmento de inversionistas responde mejor a contenido de ROI y plusvalía',
      'Las campañas de Lookalike basadas en compradores previos tienen el mejor CPL',
      'El horario óptimo de publicación es 6-8 PM entre semana',
    ],
    recommendations: [
      'Incrementar presupuesto de Meta Ads en 20% para abril',
      'Producir 4 tours virtuales adicionales para mayo',
      'Implementar programa de referidos con compradores actuales',
      'Reducir frecuencia de retargeting a máximo 4',
    ],
    nextMonthFocus: [
      'Escalar campaña de Lookalike a nuevas audiencias',
      'Lanzar campaña específica para segmento inversionistas',
      'Optimizar landing pages para mejorar conversión',
    ],
    investmentSummary: {
      total: 270000,
      byChannel: [
        { channel: 'Meta Ads', amount: 190000, percentage: 70.4 },
        { channel: 'Google Ads', amount: 80000, percentage: 29.6 },
      ]
    },
    leadsSummary: {
      total: 2163,
      qualified: 892,
      appointments: 215,
      sales: 12,
    },
    createdAt: '2024-04-01T08:00:00Z',
    approvedAt: '2024-04-03T10:00:00Z',
    sentAt: '2024-04-03T14:00:00Z',
  },
]

// AI Generation Logs Mock Data
export const mockAILogs: AIGenerationLog[] = [
  {
    id: 'log1',
    brandId: 'brand1',
    type: 'insight',
    prompt: 'Analiza el rendimiento de las campañas de Meta Ads del último mes y genera insights accionables.',
    response: 'Insight generado: Alto engagement en contenido de tours virtuales...',
    model: 'gemini-1.5-pro',
    tokens: 2450,
    cost: 0.12,
    duration: 3.2,
    status: 'success',
    createdAt: '2024-04-15T08:00:00Z',
    createdBy: 'Sistema Automático',
  },
  {
    id: 'log2',
    brandId: 'brand1',
    type: 'recommendation',
    prompt: 'Basado en los KPIs actuales, genera recomendaciones para optimizar el presupuesto del próximo mes.',
    response: 'Recomendaciones generadas: 1. Incrementar presupuesto Meta Ads...',
    model: 'gemini-1.5-pro',
    tokens: 1890,
    cost: 0.09,
    duration: 2.8,
    status: 'success',
    createdAt: '2024-04-14T16:00:00Z',
    createdBy: 'María García',
  },
  {
    id: 'log3',
    brandId: 'brand1',
    type: 'persona',
    prompt: 'Genera un buyer persona para el segmento de inversionistas inmobiliarios basado en los datos de CRM.',
    response: 'Buyer Persona generado: Roberto Méndez, 48 años, empresario...',
    model: 'gemini-1.5-pro',
    tokens: 3200,
    cost: 0.16,
    duration: 4.5,
    status: 'success',
    createdAt: '2024-04-10T11:00:00Z',
    createdBy: 'Carlos López',
  },
  {
    id: 'log4',
    brandId: 'brand1',
    type: 'report',
    prompt: 'Genera el resumen ejecutivo del reporte mensual de marzo 2024.',
    response: 'Marzo fue un mes excepcional para Residencial Bosques...',
    model: 'gemini-1.5-pro',
    tokens: 4100,
    cost: 0.21,
    duration: 5.8,
    status: 'success',
    createdAt: '2024-04-01T08:00:00Z',
    createdBy: 'Sistema Automático',
  },
  {
    id: 'log5',
    brandId: 'brand1',
    type: 'content',
    prompt: 'Genera 5 ideas de contenido para Instagram basadas en los pilares de marca.',
    response: 'Error: Brief de marca incompleto. Se requiere información adicional sobre pilares de contenido.',
    model: 'gemini-1.5-pro',
    tokens: 450,
    cost: 0.02,
    duration: 1.2,
    status: 'error',
    error: 'Brief incompleto: falta definir pilares de contenido',
    createdAt: '2024-04-08T14:00:00Z',
    createdBy: 'Ana Martínez',
  },
]

// KPIs with Status for Dashboard
export const mockKPIsWithStatus: KPIWithStatus[] = [
  { code: 'leads', name: 'Leads Totales', value: 2163, target: 2000, min: 1800, max: 2200, status: 'excellent', variance: 8.15, trend: 'up', unit: 'number' },
  { code: 'cpl', name: 'Costo por Lead', value: 95.29, target: 100, min: 50, max: 150, status: 'good', variance: -4.71, trend: 'down', unit: 'currency' },
  { code: 'roas', name: 'ROAS', value: 494, target: 400, min: 300, max: 600, status: 'excellent', variance: 23.5, trend: 'up', unit: 'number' },
  { code: 'ctr', name: 'CTR', value: 1.48, target: 1.5, min: 1.0, max: 3.0, status: 'good', variance: -1.3, trend: 'stable', unit: 'percentage' },
  { code: 'cpc', name: 'CPC', value: 4.59, target: 5.0, min: 3.0, max: 8.0, status: 'good', variance: -8.2, trend: 'down', unit: 'currency' },
  { code: 'appointments', name: 'Citas', value: 215, target: 180, min: 150, max: 220, status: 'excellent', variance: 19.4, trend: 'up', unit: 'number' },
  { code: 'sales', name: 'Ventas', value: 12, target: 10, min: 8, max: 15, status: 'excellent', variance: 20, trend: 'up', unit: 'number' },
  { code: 'frequency', name: 'Frecuencia', value: 2.78, target: 3.0, min: 2.0, max: 4.0, status: 'good', variance: -7.3, trend: 'stable', unit: 'number' },
  { code: 'er', name: 'Engagement Rate', value: 6.5, target: 5.0, min: 3.0, max: 8.0, status: 'excellent', variance: 30, trend: 'up', unit: 'percentage' },
]

// Helper function to get data by brand
export function getBrandMediaConnections(brandId: string): MediaConnection[] {
  return mockMediaConnections.filter(mc => mc.brandId === brandId || mc.brandId === 'brand1')
}

export function getBrandCampaigns(brandId: string): CampaignPerformance[] {
  return mockCampaignPerformance.filter(cp => cp.brandId === brandId || cp.brandId === 'brand1')
}

export function getBrandOrganicContent(brandId: string): OrganicContentPerformance[] {
  return mockOrganicPerformance.filter(oc => oc.brandId === brandId || oc.brandId === 'brand1')
}

export function getBrandInsights(brandId: string): AIInsight[] {
  return mockAIInsights.filter(i => i.brandId === brandId || i.brandId === 'brand1')
}

export function getBrandAlerts(brandId: string): SmartAlert[] {
  return mockSmartAlerts.filter(a => a.brandId === brandId || a.brandId === 'brand1')
}

export function getBrandReports(brandId: string): ExecutiveReport[] {
  return mockExecutiveReports.filter(r => r.brandId === brandId || r.brandId === 'brand1')
}

export function getBrandAILogs(brandId: string): AIGenerationLog[] {
  return mockAILogs.filter(l => l.brandId === brandId || l.brandId === 'brand1')
}

export function getBrandKPIs(brandId: string): KPIWithStatus[] {
  return mockKPIsWithStatus
}
