import { 
  ContentPillar, 
  ContentPiece, 
  ContentVersion,
  HeatmapData, 
  PaidCampaign, 
  Moodboard, 
  GeneratedImage, 
  GemConfig, 
  SocialConnection,
  AIGeneration,
  PublishingError
} from './brand-phase2-types'

// ============ PILARES DE CONTENIDO ============

export const mockContentPillars: ContentPillar[] = [
  {
    id: 'pillar-1',
    brandId: 'brand-1',
    name: 'Lifestyle & Aspiracional',
    description: 'Contenido que muestra el estilo de vida aspiracional del desarrollo',
    color: '#8b5cf6',
    percentage: 30,
    examples: ['Amenidades', 'Vistas', 'Espacios comunes', 'Experiencias'],
    buyerPersonaIds: ['persona-1', 'persona-2'],
    funnelStages: ['awareness', 'consideration'],
    isActive: true,
  },
  {
    id: 'pillar-2',
    brandId: 'brand-1',
    name: 'Producto & Características',
    description: 'Detalles técnicos, planos, acabados y especificaciones',
    color: '#3b82f6',
    percentage: 25,
    examples: ['Planos', 'Renders interiores', 'Acabados', 'Tecnología'],
    buyerPersonaIds: ['persona-1', 'persona-3'],
    funnelStages: ['consideration', 'conversion'],
    isActive: true,
  },
  {
    id: 'pillar-3',
    brandId: 'brand-1',
    name: 'Ubicación & Conectividad',
    description: 'Beneficios de la ubicación, cercanía a servicios y accesibilidad',
    color: '#10b981',
    percentage: 20,
    examples: ['Mapa de cercanías', 'Tiempos de traslado', 'Servicios cercanos'],
    buyerPersonaIds: ['persona-2', 'persona-4'],
    funnelStages: ['awareness', 'consideration'],
    isActive: true,
  },
  {
    id: 'pillar-4',
    brandId: 'brand-1',
    name: 'Inversión & Financiero',
    description: 'Planes de pago, plusvalía, rendimientos y beneficios financieros',
    color: '#f59e0b',
    percentage: 15,
    examples: ['Planes de pago', 'Plusvalía histórica', 'ROI estimado'],
    buyerPersonaIds: ['persona-3', 'persona-5'],
    funnelStages: ['conversion'],
    isActive: true,
  },
  {
    id: 'pillar-5',
    brandId: 'brand-1',
    name: 'Testimoniales & Social Proof',
    description: 'Historias de clientes, testimonios y casos de éxito',
    color: '#ec4899',
    percentage: 10,
    examples: ['Testimonios en video', 'Historias de compradores', 'Reviews'],
    buyerPersonaIds: ['persona-1', 'persona-2', 'persona-4'],
    funnelStages: ['consideration', 'conversion'],
    isActive: true,
  },
]

// ============ CONTENIDO ORGÁNICO ============

export const mockContentPieces: ContentPiece[] = [
  // Semana 1
  {
    id: 'content-1',
    brandId: 'brand-1',
    title: 'Despierta con vista al parque',
    description: 'Reel mostrando amanecer desde el penthouse',
    format: 'reel',
    platform: 'instagram',
    pillarId: 'pillar-1',
    buyerPersonaId: 'persona-1',
    funnelStage: 'awareness',
    status: 'published',
    copy: 'Imagina despertar cada mañana con esta vista. Torre Central Living te ofrece departamentos con vistas privilegiadas al parque más exclusivo de la ciudad.',
    hashtags: ['TorreCentralLiving', 'DepartamentosLujo', 'CDMX', 'VistaAlParque', 'VidaUrbana'],
    callToAction: 'Agenda tu visita',
    scheduledDate: '2024-03-01',
    scheduledTime: '09:00',
    publishedAt: '2024-03-01T09:00:00Z',
    internalApproval: { status: 'approved', approvedBy: 'María García', approvedAt: '2024-02-28' },
    clientApproval: { status: 'approved', approvedBy: 'Cliente', approvedAt: '2024-02-28' },
    metrics: { reach: 45000, impressions: 78000, engagement: 3200, likes: 2800, comments: 156, shares: 89, saves: 234 },
    version: 4,
    versionHistory: [
      {
        id: 'vh-1-1',
        version: 1,
        title: 'Vista al parque - borrador',
        copy: 'Borrador inicial del copy...',
        status: 'draft',
        changedBy: 'Ana López',
        changedAt: '2024-02-25T10:00:00Z',
        changeType: 'create',
        changeDescription: 'Creación inicial del contenido',
      },
      {
        id: 'vh-1-2',
        version: 2,
        title: 'Despierta con vista al parque',
        copy: 'Imagina despertar cada mañana con esta vista...',
        status: 'internal_review',
        changedBy: 'Ana López',
        changedAt: '2024-02-26T14:30:00Z',
        changeType: 'edit',
        changeDescription: 'Actualización de copy y título',
        previousValues: { title: 'Vista al parque - borrador', status: 'draft' },
      },
      {
        id: 'vh-1-3',
        version: 3,
        title: 'Despierta con vista al parque',
        status: 'approved',
        changedBy: 'María García',
        changedAt: '2024-02-28T09:15:00Z',
        changeType: 'approval',
        changeDescription: 'Aprobado por equipo interno y cliente',
        previousValues: { status: 'internal_review' },
      },
      {
        id: 'vh-1-4',
        version: 4,
        title: 'Despierta con vista al parque',
        status: 'published',
        changedBy: 'Sistema',
        changedAt: '2024-03-01T09:00:00Z',
        changeType: 'status_change',
        changeDescription: 'Publicado automáticamente según programación',
        previousValues: { status: 'scheduled' },
      },
    ],
    createdAt: '2024-02-25',
    updatedAt: '2024-03-01',
  },
  {
    id: 'content-2',
    brandId: 'brand-1',
    title: 'Conoce nuestras amenidades',
    description: 'Carrusel con las 8 principales amenidades',
    format: 'carrusel',
    platform: 'instagram',
    pillarId: 'pillar-1',
    buyerPersonaId: 'persona-2',
    funnelStage: 'consideration',
    status: 'published',
    copy: 'Más de 2,500 m² de amenidades diseñadas para elevar tu calidad de vida:\n\n✨ Rooftop con alberca infinity\n🏋️ Gimnasio equipado\n🧘 Sala de yoga\n👶 Kids club\n🐕 Pet park\n🎬 Cine privado\n💼 Coworking\n🌳 Jardín zen',
    hashtags: ['Amenidades', 'VidaDeLujo', 'TorreCentralLiving', 'CDMX'],
    scheduledDate: '2024-03-03',
    scheduledTime: '12:00',
    publishedAt: '2024-03-03T12:00:00Z',
    internalApproval: { status: 'approved' },
    clientApproval: { status: 'approved' },
    metrics: { reach: 38000, impressions: 62000, engagement: 2800, likes: 2400, comments: 89, shares: 45, saves: 312 },
    version: 1,
    createdAt: '2024-02-26',
    updatedAt: '2024-03-03',
  },
  {
    id: 'content-3',
    brandId: 'brand-1',
    title: 'Plano departamento 2 recámaras',
    description: 'Post con plano arquitectónico detallado',
    format: 'imagen',
    platform: 'instagram',
    pillarId: 'pillar-2',
    buyerPersonaId: 'persona-4',
    funnelStage: 'consideration',
    status: 'scheduled',
    copy: '98 m² perfectamente diseñados para tu familia.\n\n📐 2 recámaras con closet\n🛁 2 baños completos\n🍳 Cocina integral\n🛋️ Sala-comedor con terraza\n🚗 1 cajón de estacionamiento',
    hashtags: ['Planos', 'Arquitectura', 'DepartamentosFamiliares', 'TorreCentralLiving'],
    scheduledDate: '2024-03-15',
    scheduledTime: '11:00',
    internalApproval: { status: 'approved' },
    clientApproval: { status: 'approved' },
    version: 1,
    createdAt: '2024-03-01',
    updatedAt: '2024-03-10',
  },
  {
    id: 'content-4',
    brandId: 'brand-1',
    title: 'A 5 minutos de todo',
    description: 'Mapa interactivo de conectividad',
    format: 'carrusel',
    platform: 'facebook',
    pillarId: 'pillar-3',
    buyerPersonaId: 'persona-2',
    funnelStage: 'awareness',
    status: 'internal_review',
    copy: 'Ubicación estratégica que te conecta con lo mejor de la ciudad:\n\n🏢 Santa Fe: 8 min\n🛒 Perisur: 12 min\n✈️ Aeropuerto: 25 min\n🏥 Hospital ABC: 10 min',
    hashtags: ['Ubicación', 'CDMX', 'Conectividad'],
    internalApproval: { status: 'pending' },
    version: 1,
    createdAt: '2024-03-05',
    updatedAt: '2024-03-12',
  },
  {
    id: 'content-5',
    brandId: 'brand-1',
    title: 'Plan de pagos flexible',
    description: 'Infografía con opciones de financiamiento',
    format: 'imagen',
    platform: 'linkedin',
    pillarId: 'pillar-4',
    buyerPersonaId: 'persona-3',
    funnelStage: 'conversion',
    status: 'draft',
    copy: 'Invertir en Torre Central Living es más accesible de lo que piensas.\n\n💰 Enganche desde 10%\n📅 36 meses sin intereses\n🏦 Crédito bancario disponible\n📈 Plusvalía proyectada: 12% anual',
    internalApproval: { status: 'pending' },
    version: 1,
    createdAt: '2024-03-08',
    updatedAt: '2024-03-08',
  },
  {
    id: 'content-6',
    brandId: 'brand-1',
    title: 'Historia de éxito: Familia Martínez',
    description: 'Video testimonial de compradores',
    format: 'video',
    platform: 'instagram',
    pillarId: 'pillar-5',
    buyerPersonaId: 'persona-4',
    funnelStage: 'conversion',
    status: 'design',
    copy: '"Encontramos el hogar perfecto para nuestra familia" - Familia Martínez\n\nDescubre por qué eligieron Torre Central Living.',
    internalApproval: { status: 'pending' },
    version: 1,
    createdAt: '2024-03-10',
    updatedAt: '2024-03-11',
  },
  // Más contenido para diferentes estados
  {
    id: 'content-7',
    brandId: 'brand-1',
    title: 'Render cocina modelo A',
    format: 'imagen',
    platform: 'instagram',
    pillarId: 'pillar-2',
    funnelStage: 'consideration',
    status: 'idea',
    version: 1,
    createdAt: '2024-03-12',
    updatedAt: '2024-03-12',
  },
  {
    id: 'content-8',
    brandId: 'brand-1',
    title: 'Reel recorrido virtual',
    format: 'reel',
    platform: 'tiktok',
    pillarId: 'pillar-1',
    funnelStage: 'awareness',
    status: 'writing',
    version: 1,
    createdAt: '2024-03-11',
    updatedAt: '2024-03-12',
  },
  {
    id: 'content-9',
    brandId: 'brand-1',
    title: 'Story countdown evento',
    format: 'story',
    platform: 'instagram',
    pillarId: 'pillar-1',
    funnelStage: 'conversion',
    status: 'client_review',
    internalApproval: { status: 'approved' },
    clientApproval: { status: 'pending' },
    version: 1,
    createdAt: '2024-03-09',
    updatedAt: '2024-03-13',
  },
  {
    id: 'content-10',
    brandId: 'brand-1',
    title: 'Artículo: Guía del comprador',
    format: 'article',
    platform: 'linkedin',
    pillarId: 'pillar-4',
    funnelStage: 'consideration',
    status: 'approved',
    internalApproval: { status: 'approved' },
    clientApproval: { status: 'approved' },
    scheduledDate: '2024-03-20',
    scheduledTime: '10:00',
    version: 1,
    createdAt: '2024-03-01',
    updatedAt: '2024-03-14',
  },
]

// ============ HEATMAP DATA ============

export const mockHeatmapData: HeatmapData[] = [
  {
    brandId: 'brand-1',
    platform: 'instagram',
    lastUpdated: '2024-03-15',
    dataPoints: 150,
    data: [
      // Lunes
      { hour: 7, dayOfWeek: 1, score: 45, engagementRate: 2.1 },
      { hour: 8, dayOfWeek: 1, score: 62, engagementRate: 3.2 },
      { hour: 9, dayOfWeek: 1, score: 78, engagementRate: 4.1 },
      { hour: 12, dayOfWeek: 1, score: 85, engagementRate: 4.8 },
      { hour: 13, dayOfWeek: 1, score: 72, engagementRate: 3.9 },
      { hour: 18, dayOfWeek: 1, score: 65, engagementRate: 3.4 },
      { hour: 19, dayOfWeek: 1, score: 82, engagementRate: 4.5 },
      { hour: 20, dayOfWeek: 1, score: 88, engagementRate: 5.2 },
      { hour: 21, dayOfWeek: 1, score: 75, engagementRate: 4.0 },
      // Martes
      { hour: 9, dayOfWeek: 2, score: 80, engagementRate: 4.3 },
      { hour: 12, dayOfWeek: 2, score: 90, engagementRate: 5.1 },
      { hour: 19, dayOfWeek: 2, score: 85, engagementRate: 4.7 },
      { hour: 20, dayOfWeek: 2, score: 92, engagementRate: 5.5 },
      // Miércoles
      { hour: 9, dayOfWeek: 3, score: 75, engagementRate: 4.0 },
      { hour: 12, dayOfWeek: 3, score: 88, engagementRate: 4.9 },
      { hour: 20, dayOfWeek: 3, score: 85, engagementRate: 4.6 },
      // Jueves
      { hour: 9, dayOfWeek: 4, score: 82, engagementRate: 4.4 },
      { hour: 12, dayOfWeek: 4, score: 78, engagementRate: 4.2 },
      { hour: 19, dayOfWeek: 4, score: 88, engagementRate: 5.0 },
      { hour: 20, dayOfWeek: 4, score: 95, engagementRate: 5.8 },
      // Viernes
      { hour: 9, dayOfWeek: 5, score: 70, engagementRate: 3.8 },
      { hour: 12, dayOfWeek: 5, score: 75, engagementRate: 4.0 },
      { hour: 18, dayOfWeek: 5, score: 82, engagementRate: 4.5 },
      // Sábado
      { hour: 10, dayOfWeek: 6, score: 88, engagementRate: 5.0 },
      { hour: 11, dayOfWeek: 6, score: 92, engagementRate: 5.4 },
      { hour: 12, dayOfWeek: 6, score: 85, engagementRate: 4.7 },
      { hour: 17, dayOfWeek: 6, score: 78, engagementRate: 4.2 },
      // Domingo
      { hour: 10, dayOfWeek: 0, score: 80, engagementRate: 4.3 },
      { hour: 11, dayOfWeek: 0, score: 85, engagementRate: 4.6 },
      { hour: 19, dayOfWeek: 0, score: 75, engagementRate: 4.0 },
      { hour: 20, dayOfWeek: 0, score: 82, engagementRate: 4.5 },
    ],
  },
]

// ============ CAMPAÑAS PAGADAS ============

export const mockPaidCampaigns: PaidCampaign[] = [
  {
    id: 'campaign-1',
    brandId: 'brand-1',
    name: 'Lanzamiento Torre Central - Awareness',
    platform: 'meta',
    objective: 'awareness',
    status: 'active',
    budget: 150000,
    budgetType: 'lifetime',
    startDate: '2024-03-01',
    endDate: '2024-03-31',
    funnelStage: 'awareness',
    targetKPIs: {
      cpm: { min: 30, max: 80, target: 50 },
      ctr: { min: 0.8, max: 2.5, target: 1.5 },
    },
    metrics: {
      impressions: 2500000,
      reach: 1800000,
      clicks: 35000,
      ctr: 1.4,
      spend: 125000,
      leads: 0,
      cpl: 0,
      conversions: 0,
      cpa: 0,
      revenue: 0,
      roas: 0,
    },
    adSets: [
      {
        id: 'adset-1',
        campaignId: 'campaign-1',
        name: 'Inversionistas 35-55 CDMX',
        status: 'active',
        budget: 75000,
        budgetType: 'lifetime',
        startDate: '2024-03-01',
        targeting: {
          locations: ['Ciudad de México', 'Estado de México'],
          ageMin: 35,
          ageMax: 55,
          genders: ['all'],
          interests: ['Inversiones inmobiliarias', 'Bienes raíces', 'Finanzas personales'],
          incomeLevel: ['Alto'],
        },
        buyerPersonaId: 'persona-3',
        placements: ['facebook_feed', 'instagram_feed', 'instagram_stories'],
        ads: [
          {
            id: 'ad-1',
            adSetId: 'adset-1',
            name: 'Video Lifestyle 15s',
            format: 'video',
            status: 'active',
            primaryText: 'Invierte en el corazón de la ciudad con rendimientos proyectados del 12% anual.',
            headline: 'Torre Central Living',
            callToAction: 'Más información',
            metrics: { impressions: 850000, clicks: 12500, ctr: 1.47, spend: 42000, conversions: 0, cpc: 3.36, cpm: 49.41 },
          },
          {
            id: 'ad-2',
            adSetId: 'adset-1',
            name: 'Carrusel Amenidades',
            format: 'carousel',
            status: 'active',
            primaryText: 'Descubre las amenidades que elevarán tu inversión.',
            headline: 'Más de 2,500 m² de amenidades',
            callToAction: 'Ver más',
            metrics: { impressions: 650000, clicks: 8500, ctr: 1.31, spend: 33000, conversions: 0, cpc: 3.88, cpm: 50.77 },
          },
        ],
        metrics: { impressions: 1500000, reach: 1100000, clicks: 21000, ctr: 1.4, spend: 75000, leads: 0, cpl: 0, conversions: 0, cpa: 0 },
      },
      {
        id: 'adset-2',
        campaignId: 'campaign-1',
        name: 'Familias 30-45 CDMX',
        status: 'active',
        budget: 75000,
        budgetType: 'lifetime',
        startDate: '2024-03-01',
        targeting: {
          locations: ['Ciudad de México'],
          ageMin: 30,
          ageMax: 45,
          genders: ['all'],
          interests: ['Familia', 'Hogar', 'Educación privada'],
          behaviors: ['Padres con hijos menores'],
        },
        buyerPersonaId: 'persona-4',
        placements: ['facebook_feed', 'instagram_feed', 'instagram_reels'],
        ads: [
          {
            id: 'ad-3',
            adSetId: 'adset-2',
            name: 'Video Familia Feliz',
            format: 'video',
            status: 'active',
            primaryText: 'El hogar que tu familia merece, con espacios diseñados para crecer juntos.',
            headline: 'Departamentos familiares',
            callToAction: 'Agenda tu visita',
            metrics: { impressions: 700000, clicks: 10000, ctr: 1.43, spend: 35000, conversions: 0, cpc: 3.5, cpm: 50 },
          },
        ],
        metrics: { impressions: 1000000, reach: 700000, clicks: 14000, ctr: 1.4, spend: 50000, leads: 0, cpl: 0, conversions: 0, cpa: 0 },
      },
    ],
    createdAt: '2024-02-15',
    updatedAt: '2024-03-15',
  },
  {
    id: 'campaign-2',
    brandId: 'brand-1',
    name: 'Generación de Leads - Marzo',
    platform: 'meta',
    objective: 'leads',
    status: 'active',
    budget: 200000,
    budgetType: 'lifetime',
    startDate: '2024-03-01',
    endDate: '2024-03-31',
    funnelStage: 'conversion',
    targetKPIs: {
      cpl: { min: 150, max: 400, target: 250 },
      ctr: { min: 1, max: 3, target: 2 },
    },
    metrics: {
      impressions: 1800000,
      reach: 1200000,
      clicks: 42000,
      ctr: 2.33,
      spend: 165000,
      leads: 580,
      cpl: 284.48,
      conversions: 45,
      cpa: 3666.67,
      revenue: 0,
      roas: 0,
    },
    adSets: [
      {
        id: 'adset-3',
        campaignId: 'campaign-2',
        name: 'Remarketing Visitantes Web',
        status: 'active',
        budget: 80000,
        budgetType: 'lifetime',
        startDate: '2024-03-01',
        targeting: {
          customAudiences: ['website_visitors_30d', 'engaged_ig_30d'],
        },
        placements: ['facebook_feed', 'instagram_feed', 'instagram_stories', 'audience_network'],
        ads: [
          {
            id: 'ad-4',
            adSetId: 'adset-3',
            name: 'Lead Form - Promoción Marzo',
            format: 'image',
            status: 'active',
            primaryText: '¡Últimas unidades con precio de preventa! Agenda tu cita y recibe un 5% de descuento adicional.',
            headline: 'Promoción exclusiva marzo',
            callToAction: 'Registrarse',
            metrics: { impressions: 600000, clicks: 18000, ctr: 3.0, spend: 65000, conversions: 320, cpc: 3.61, cpm: 108.33 },
          },
        ],
        metrics: { impressions: 600000, reach: 350000, clicks: 18000, ctr: 3.0, spend: 65000, leads: 320, cpl: 203.13, conversions: 25, cpa: 2600 },
      },
    ],
    createdAt: '2024-02-20',
    updatedAt: '2024-03-15',
  },
  {
    id: 'campaign-3',
    brandId: 'brand-1',
    name: 'Google Search - Intención',
    platform: 'google',
    objective: 'leads',
    status: 'active',
    budget: 100000,
    budgetType: 'lifetime',
    startDate: '2024-03-01',
    endDate: '2024-03-31',
    funnelStage: 'conversion',
    targetKPIs: {
      cpl: { min: 200, max: 500, target: 350 },
      ctr: { min: 3, max: 8, target: 5 },
    },
    metrics: {
      impressions: 450000,
      reach: 0,
      clicks: 22500,
      ctr: 5.0,
      spend: 78000,
      leads: 210,
      cpl: 371.43,
      conversions: 18,
      cpa: 4333.33,
      revenue: 0,
      roas: 0,
    },
    adSets: [],
    createdAt: '2024-02-25',
    updatedAt: '2024-03-15',
  },
]

// ============ MOODBOARDS ============

export const mockMoodboards: Moodboard[] = [
  {
    id: 'moodboard-1',
    brandId: 'brand-1',
    name: 'Estilo de Vida Urbano Premium',
    description: 'Moodboard principal para contenido lifestyle de Torre Central Living',
    purpose: 'general',
    references: [
      { id: 'ref-1', url: '/placeholder.svg?height=300&width=400', description: 'Arquitectura moderna minimalista', tags: ['arquitectura', 'minimalista'] },
      { id: 'ref-2', url: '/placeholder.svg?height=300&width=400', description: 'Interiores contemporáneos', tags: ['interiores', 'lujo'] },
      { id: 'ref-3', url: '/placeholder.svg?height=300&width=400', description: 'Lifestyle urbano', tags: ['lifestyle', 'urbano'] },
      { id: 'ref-4', url: '/placeholder.svg?height=300&width=400', description: 'Amenidades premium', tags: ['amenidades', 'premium'] },
    ],
    colorPalette: {
      primary: '#1a1a2e',
      secondary: '#16213e',
      accent: '#c9a959',
      background: '#f8f9fa',
      text: '#1a1a2e',
      additional: ['#e8e8e8', '#2d2d44'],
    },
    typography: {
      primary: 'Playfair Display',
      secondary: 'Inter',
      accent: 'Cormorant Garamond',
    },
    styleKeywords: ['elegante', 'sofisticado', 'moderno', 'premium', 'urbano'],
    moodKeywords: ['aspiracional', 'exclusivo', 'sereno', 'luminoso'],
    status: 'approved',
    approvedBy: 'Director Creativo',
    approvedAt: '2024-02-15',
    createdAt: '2024-02-10',
    updatedAt: '2024-02-15',
  },
  {
    id: 'moodboard-2',
    brandId: 'brand-1',
    name: 'Campaña Inversionistas',
    description: 'Visual direction para campaña de captación de inversionistas',
    purpose: 'campaign',
    campaignId: 'campaign-2',
    buyerPersonaId: 'persona-3',
    references: [
      { id: 'ref-5', url: '/placeholder.svg?height=300&width=400', description: 'Gráficos financieros elegantes', tags: ['finanzas', 'gráficos'] },
      { id: 'ref-6', url: '/placeholder.svg?height=300&width=400', description: 'Arquitectura como inversión', tags: ['inversión', 'arquitectura'] },
    ],
    colorPalette: {
      primary: '#0f172a',
      secondary: '#1e3a5f',
      accent: '#22c55e',
      background: '#ffffff',
      text: '#0f172a',
    },
    styleKeywords: ['profesional', 'confiable', 'sólido', 'rentable'],
    moodKeywords: ['seguridad', 'crecimiento', 'oportunidad'],
    status: 'approved',
    createdAt: '2024-02-20',
    updatedAt: '2024-02-25',
  },
  {
    id: 'moodboard-3',
    brandId: 'brand-1',
    name: 'Familia Joven',
    description: 'Visual direction para buyer persona familia con hijos',
    purpose: 'persona',
    buyerPersonaId: 'persona-4',
    references: [
      { id: 'ref-7', url: '/placeholder.svg?height=300&width=400', description: 'Momentos familiares', tags: ['familia', 'momentos'] },
      { id: 'ref-8', url: '/placeholder.svg?height=300&width=400', description: 'Espacios para niños', tags: ['niños', 'espacios'] },
    ],
    colorPalette: {
      primary: '#2563eb',
      secondary: '#7c3aed',
      accent: '#f59e0b',
      background: '#fef3c7',
      text: '#1f2937',
    },
    styleKeywords: ['cálido', 'acogedor', 'seguro', 'divertido'],
    moodKeywords: ['felicidad', 'tranquilidad', 'futuro', 'hogar'],
    status: 'draft',
    createdAt: '2024-03-01',
    updatedAt: '2024-03-05',
  },
]

// ============ IMÁGENES GENERADAS ============

export const mockGeneratedImages: GeneratedImage[] = [
  {
    id: 'genimg-1',
    brandId: 'brand-1',
    prompt: 'Luxurious modern penthouse living room with floor-to-ceiling windows overlooking Mexico City skyline at golden hour, minimalist furniture, warm lighting, photorealistic, architectural photography style',
    format: '16:9',
    width: 1920,
    height: 1080,
    imageUrl: '/placeholder.svg?height=1080&width=1920',
    thumbnailUrl: '/placeholder.svg?height=270&width=480',
    moodboardId: 'moodboard-1',
    model: 'gemini-imagen-3',
    style: 'photorealistic',
    status: 'approved',
    usedIn: ['content'],
    generatedBy: 'María García',
    generatedAt: '2024-03-01T10:30:00Z',
    tokensUsed: 1500,
  },
  {
    id: 'genimg-2',
    brandId: 'brand-1',
    prompt: 'Aerial view of exclusive residential tower with infinity pool on rooftop, surrounded by lush gardens, modern architecture, Mexico City, cinematic lighting',
    format: '1:1',
    width: 1080,
    height: 1080,
    imageUrl: '/placeholder.svg?height=1080&width=1080',
    thumbnailUrl: '/placeholder.svg?height=270&width=270',
    moodboardId: 'moodboard-1',
    model: 'gemini-imagen-3',
    style: 'architectural',
    status: 'completed',
    generatedBy: 'Carlos López',
    generatedAt: '2024-03-05T14:20:00Z',
    tokensUsed: 1200,
  },
  {
    id: 'genimg-3',
    brandId: 'brand-1',
    prompt: 'Young professional family enjoying breakfast in modern kitchen with city views, warm morning light, lifestyle photography, aspirational',
    format: '4:5',
    width: 1080,
    height: 1350,
    imageUrl: '/placeholder.svg?height=1350&width=1080',
    thumbnailUrl: '/placeholder.svg?height=337&width=270',
    buyerPersonaId: 'persona-4',
    moodboardId: 'moodboard-3',
    model: 'gemini-imagen-3',
    style: 'lifestyle',
    status: 'approved',
    usedIn: ['content', 'campaign'],
    generatedBy: 'Ana Martínez',
    generatedAt: '2024-03-08T09:15:00Z',
    tokensUsed: 1350,
  },
]

// ============ GEMS CONFIGURADOS ============

export const mockGemConfigs: GemConfig[] = [
  {
    id: 'gem-1',
    brandId: 'brand-1',
    type: 'brief_strategist',
    name: 'Brief Strategist - Torre Central',
    description: 'Analiza y completa el brief estratégico de la marca con enfoque en real estate de lujo',
    provider: 'gemini',
    model: 'gemini-2.0-pro',
    systemPrompt: `Eres un estratega de marketing especializado en real estate de lujo en México. Tu rol es analizar y completar briefs de marca asegurando que contengan toda la información necesaria para crear campañas efectivas.

Conoces profundamente:
- El mercado inmobiliario mexicano y sus tendencias
- Los buyer personas típicos del segmento premium
- Las mejores prácticas de comunicación para desarrollos de lujo
- Los canales digitales más efectivos para este segmento

Siempre respondes en español y mantienes un tono profesional pero accesible.`,
    includeContext: { brandProfile: true, brief: true, buyerPersonas: true, objectives: true, competitors: true, previousContent: false, moodboards: false },
    temperature: 0.7,
    maxTokens: 4096,
    canEdit: ['admin', 'director'],
    canUse: ['admin', 'director', 'manager'],
    isActive: true,
    usageCount: 45,
    lastUsedAt: '2024-03-14T16:30:00Z',
    createdAt: '2024-02-01',
    updatedAt: '2024-03-01',
  },
  {
    id: 'gem-2',
    brandId: 'brand-1',
    type: 'copywriter',
    name: 'Copywriter Premium - Torre Central',
    description: 'Genera copies persuasivos para redes sociales y campañas pagadas',
    provider: 'gemini',
    model: 'gemini-2.0-flash',
    systemPrompt: `Eres un copywriter experto en marketing inmobiliario de lujo. Creas textos que:
- Conectan emocionalmente con el público objetivo
- Destacan beneficios sobre características
- Usan un tono aspiracional pero auténtico
- Se adaptan a cada plataforma (Instagram, Facebook, LinkedIn)
- Incluyen calls to action efectivos

Siempre consideras el buyer persona al escribir y ajustas el mensaje según la etapa del funnel.`,
    includeContext: { brandProfile: true, brief: true, buyerPersonas: true, objectives: false, competitors: false, previousContent: true, moodboards: false },
    temperature: 0.9,
    maxTokens: 2048,
    canEdit: ['admin', 'director', 'manager'],
    canUse: ['admin', 'director', 'manager', 'creator'],
    isActive: true,
    usageCount: 128,
    lastUsedAt: '2024-03-15T11:20:00Z',
    createdAt: '2024-02-01',
    updatedAt: '2024-03-01',
  },
  {
    id: 'gem-3',
    brandId: 'brand-1',
    type: 'content_planner',
    name: 'Content Planner - Torre Central',
    description: 'Planifica el contenido mensual alineado a objetivos y pilares',
    provider: 'gemini',
    model: 'gemini-2.0-pro',
    systemPrompt: `Eres un planificador de contenido digital especializado en real estate. Tu rol es crear calendarios de contenido que:
- Balancean los pilares de contenido definidos
- Cubren todas las etapas del funnel
- Aprovechan tendencias y fechas relevantes
- Optimizan para engagement en cada plataforma
- Mantienen consistencia de marca`,
    includeContext: { brandProfile: true, brief: true, buyerPersonas: true, objectives: true, competitors: false, previousContent: true, moodboards: false },
    temperature: 0.8,
    maxTokens: 4096,
    canEdit: ['admin', 'director'],
    canUse: ['admin', 'director', 'manager'],
    isActive: true,
    usageCount: 32,
    lastUsedAt: '2024-03-10T09:00:00Z',
    createdAt: '2024-02-01',
    updatedAt: '2024-03-01',
  },
  {
    id: 'gem-4',
    brandId: 'brand-1',
    type: 'visual_director',
    name: 'Visual Director - Torre Central',
    description: 'Genera prompts visuales y dirige el estilo creativo de las imágenes',
    provider: 'gemini',
    model: 'gemini-2.0-pro',
    systemPrompt: `Eres un director creativo visual especializado en fotografía arquitectónica y lifestyle de lujo. Generas prompts detallados para:
- Imágenes fotorrealistas de interiores y exteriores
- Fotografía de estilo de vida aspiracional
- Renders arquitectónicos profesionales
- Contenido visual para redes sociales

Tus prompts son detallados e incluyen: composición, iluminación, estilo, mood, colores dominantes y referencias visuales.`,
    includeContext: { brandProfile: true, brief: true, buyerPersonas: true, objectives: false, competitors: false, previousContent: false, moodboards: true },
    temperature: 0.85,
    maxTokens: 2048,
    canEdit: ['admin', 'director'],
    canUse: ['admin', 'director', 'manager', 'creator'],
    isActive: true,
    usageCount: 67,
    lastUsedAt: '2024-03-14T14:45:00Z',
    createdAt: '2024-02-01',
    updatedAt: '2024-03-01',
  },
  {
    id: 'gem-5',
    brandId: 'brand-1',
    type: 'paid_strategist',
    name: 'Paid Media Strategist - Torre Central',
    description: 'Planifica campañas pagadas y genera segmentaciones',
    provider: 'gemini',
    model: 'gemini-2.0-pro',
    systemPrompt: `Eres un estratega de medios pagados experto en Meta Ads y Google Ads para real estate de lujo. Creas:
- Estructuras de campaña optimizadas
- Segmentaciones basadas en buyer personas
- Recomendaciones de presupuesto
- Estrategias de bidding
- Copies y CTAs para anuncios`,
    includeContext: { brandProfile: true, brief: true, buyerPersonas: true, objectives: true, competitors: true, previousContent: false, moodboards: false },
    temperature: 0.7,
    maxTokens: 4096,
    canEdit: ['admin', 'director'],
    canUse: ['admin', 'director', 'manager'],
    isActive: true,
    usageCount: 24,
    lastUsedAt: '2024-03-12T10:30:00Z',
    createdAt: '2024-02-01',
    updatedAt: '2024-03-01',
  },
  {
    id: 'gem-6',
    brandId: 'brand-1',
    type: 'data_analyst',
    name: 'Data Analyst - Torre Central',
    description: 'Analiza métricas y genera insights accionables',
    provider: 'gemini',
    model: 'gemini-2.0-flash',
    systemPrompt: `Eres un analista de datos de marketing digital. Analizas métricas y generas:
- Insights accionables
- Recomendaciones de optimización
- Identificación de patrones y tendencias
- Alertas de rendimiento
- Reportes ejecutivos concisos`,
    includeContext: { brandProfile: true, brief: false, buyerPersonas: true, objectives: true, competitors: true, previousContent: true, moodboards: false },
    temperature: 0.5,
    maxTokens: 4096,
    canEdit: ['admin', 'director'],
    canUse: ['admin', 'director', 'manager', 'analyst'],
    isActive: true,
    usageCount: 89,
    lastUsedAt: '2024-03-15T08:00:00Z',
    createdAt: '2024-02-01',
    updatedAt: '2024-03-01',
  },
]

// ============ CONEXIONES SOCIALES ============

export const mockSocialConnections: SocialConnection[] = [
  {
    id: 'social-1',
    brandId: 'brand-1',
    platform: 'instagram',
    accountId: '123456789',
    accountName: 'Torre Central Living',
    accountHandle: '@torrecentralliving',
    profileImageUrl: '/placeholder.svg?height=100&width=100',
    status: 'connected',
    connectedAt: '2024-01-15T10:00:00Z',
    lastSyncAt: '2024-03-15T12:00:00Z',
    permissions: ['publish_content', 'read_insights', 'manage_comments'],
    canPublish: true,
    canSchedule: true,
    canAnalyze: true,
    followers: 45200,
    following: 890,
    posts: 234,
  },
  {
    id: 'social-2',
    brandId: 'brand-1',
    platform: 'facebook',
    accountId: '987654321',
    accountName: 'Torre Central Living',
    profileImageUrl: '/placeholder.svg?height=100&width=100',
    status: 'connected',
    connectedAt: '2024-01-15T10:05:00Z',
    lastSyncAt: '2024-03-15T12:00:00Z',
    permissions: ['publish_content', 'read_insights', 'manage_ads'],
    canPublish: true,
    canSchedule: true,
    canAnalyze: true,
    followers: 28500,
    posts: 189,
  },
  {
    id: 'social-3',
    brandId: 'brand-1',
    platform: 'linkedin',
    accountId: '456789123',
    accountName: 'Torre Central Living',
    accountHandle: 'torre-central-living',
    profileImageUrl: '/placeholder.svg?height=100&width=100',
    status: 'connected',
    connectedAt: '2024-02-01T14:30:00Z',
    lastSyncAt: '2024-03-15T12:00:00Z',
    permissions: ['publish_content', 'read_insights'],
    canPublish: true,
    canSchedule: true,
    canAnalyze: true,
    followers: 12800,
    posts: 67,
  },
  {
    id: 'social-4',
    brandId: 'brand-1',
    platform: 'tiktok',
    accountId: '789123456',
    accountName: 'Torre Central Living',
    accountHandle: '@torrecentralliving',
    profileImageUrl: '/placeholder.svg?height=100&width=100',
    status: 'expired',
    connectedAt: '2024-01-20T09:00:00Z',
    expiresAt: '2024-03-10T09:00:00Z',
    lastSyncAt: '2024-03-10T09:00:00Z',
    permissions: ['publish_content'],
    canPublish: false,
    canSchedule: false,
    canAnalyze: false,
    errorMessage: 'Token expirado. Por favor reconecta la cuenta.',
    followers: 8900,
    posts: 45,
  },
  {
    id: 'social-5',
    brandId: 'brand-1',
    platform: 'youtube',
    accountId: '321654987',
    accountName: 'Torre Central Living',
    accountHandle: '@TorreCentralLiving',
    profileImageUrl: '/placeholder.svg?height=100&width=100',
    status: 'disconnected',
    permissions: [],
    canPublish: false,
    canSchedule: false,
    canAnalyze: false,
  },
]

// ============ AI GENERATIONS ============

export const mockAIGenerations: AIGeneration[] = [
  {
    id: 'aigen-1',
    brandId: 'brand-1',
    gemId: 'gem-2',
    type: 'copy',
    prompt: 'Genera un copy para Instagram sobre las amenidades del desarrollo, enfocado en familias jóvenes',
    response: `✨ Tu nuevo hogar te espera con más de 2,500 m² de amenidades diseñadas para cada momento en familia.

🏊 Alberca infinity con vista panorámica
🧘 Sala de yoga y meditación
👶 Kids club para los pequeños
🐕 Pet park para tu mejor amigo
🎬 Cine privado para las noches de película
💼 Coworking para equilibrar trabajo y vida

Agenda tu visita y descubre el estilo de vida que merece tu familia. 🏠

#TorreCentralLiving #DepartamentosEnVenta #CDMX #VidaEnFamilia`,
    contextUsed: ['brandProfile', 'brief', 'buyerPersonas'],
    model: 'gemini-2.0-flash',
    tokensInput: 450,
    tokensOutput: 180,
    duration: 2340,
    rating: 5,
    wasUsed: true,
    createdAt: '2024-03-14T10:30:00Z',
    createdBy: 'María García',
  },
  {
    id: 'aigen-2',
    brandId: 'brand-1',
    gemId: 'gem-4',
    type: 'content',
    prompt: 'Genera un prompt para crear una imagen de la terraza del penthouse al atardecer',
    response: `Luxurious penthouse rooftop terrace at golden hour in Mexico City. Modern minimalist furniture with neutral tones, infinity-edge plunge pool reflecting the warm sky. Panoramic view of the city skyline with mountains in the background. Soft ambient lighting from recessed fixtures. A couple enjoying wine, lifestyle photography, Canon EOS R5, 24mm lens, shallow depth of field, cinematic color grading with warm golden tones. Architectural Digest style, photorealistic, high resolution.

Negative prompt: cartoon, illustration, low quality, blurry, oversaturated`,
    contextUsed: ['brandProfile', 'moodboards'],
    model: 'gemini-2.0-pro',
    tokensInput: 380,
    tokensOutput: 120,
    duration: 1890,
    rating: 4,
    wasUsed: true,
    createdAt: '2024-03-14T14:45:00Z',
    createdBy: 'Carlos López',
  },
]

// ============ PUBLISHING ERRORS ============

export const mockPublishingErrors: PublishingError[] = [
  {
    id: 'error-1',
    brandId: 'brand-1',
    contentPieceId: 'content-3',
    platform: 'tiktok',
    errorType: 'auth',
    errorMessage: 'Token de acceso expirado. Se requiere reconexión de la cuenta.',
    errorCode: 'AUTH_TOKEN_EXPIRED',
    retryable: false,
    createdAt: '2024-03-10T09:15:00Z',
  },
  {
    id: 'error-2',
    brandId: 'brand-1',
    contentPieceId: 'content-5',
    platform: 'instagram',
    errorType: 'content',
    errorMessage: 'El video excede la duración máxima permitida para Reels (90 segundos).',
    errorCode: 'VIDEO_TOO_LONG',
    retryable: true,
    createdAt: '2024-03-12T16:30:00Z',
  },
]
