// Phase 3 Mock Data for Marketing Intelligence
import type {
  Report,
  ReportTemplate,
  ReportHistory,
  AiInsight,
  AiTask,
  Alert,
  AlertRule,
  User,
  RolePermissions,
  AuditLog,
  Settings,
  DataBlend,
  DataDestinationConfig,
  SyncLog,
  CustomConnector,
} from './types-phase3'

// ==================== REPORT TEMPLATES ====================
export const mockReportTemplates: ReportTemplate[] = [
  {
    id: 'tpl-1',
    name: 'Reporte Ejecutivo',
    description: 'Resumen ejecutivo completo para directivos',
    sections: ['portada', 'resumen', 'kpis', 'canales', 'conclusiones'],
  },
  {
    id: 'tpl-2',
    name: 'Reporte Pauta Digital',
    description: 'Análisis detallado de campañas pagadas',
    sections: ['portada', 'resumen', 'kpis', 'campanas', 'leads', 'conclusiones'],
  },
  {
    id: 'tpl-3',
    name: 'Reporte Redes Sociales',
    description: 'Performance de contenido orgánico',
    sections: ['portada', 'resumen', 'engagement', 'contenido', 'conclusiones'],
  },
  {
    id: 'tpl-4',
    name: 'Reporte SEO',
    description: 'Posicionamiento y tráfico orgánico',
    sections: ['portada', 'resumen', 'keywords', 'trafico', 'backlinks', 'conclusiones'],
  },
  {
    id: 'tpl-5',
    name: 'Reporte Leads y CRM',
    description: 'Análisis de generación y calidad de leads',
    sections: ['portada', 'resumen', 'leads', 'funnel', 'calidad', 'conclusiones'],
  },
  {
    id: 'tpl-6',
    name: 'Reporte Inmobiliario',
    description: 'Especializado para proyectos inmobiliarios',
    sections: ['portada', 'resumen', 'leads', 'visitas', 'ventas', 'conclusiones'],
  },
  {
    id: 'tpl-7',
    name: 'Reporte Omnicanal',
    description: 'Visión 360° de todos los canales',
    sections: ['portada', 'resumen', 'kpis', 'canales', 'organico', 'seo', 'conclusiones'],
  },
  {
    id: 'tpl-8',
    name: 'Reporte Comparativo Mensual',
    description: 'Comparación mes a mes',
    sections: ['portada', 'resumen', 'comparativo', 'tendencias', 'conclusiones'],
  },
  {
    id: 'tpl-9',
    name: 'Reporte de Campañas',
    description: 'Detalle por campaña individual',
    sections: ['portada', 'resumen', 'campana', 'creativos', 'conclusiones'],
  },
  {
    id: 'tpl-10',
    name: 'Reporte de Contenido',
    description: 'Análisis de contenido publicado',
    sections: ['portada', 'resumen', 'posts', 'engagement', 'mejores', 'conclusiones'],
  },
]

// ==================== REPORTS ====================
export const mockReports: Report[] = [
  {
    id: 'rpt-1',
    name: 'Reporte Mensual - Vertex',
    clientId: 'client-1',
    clientName: 'Vertex Inmobiliaria',
    brandId: 'brand-1',
    brandName: 'Torre Skyline',
    templateId: 'tpl-1',
    templateName: 'Reporte Ejecutivo',
    frequency: 'mensual',
    sections: [
      { id: 's1', name: 'Portada', type: 'image', module: 'general', enabled: true, order: 1 },
      { id: 's2', name: 'Resumen Ejecutivo', type: 'text', module: 'general', enabled: true, order: 2 },
      { id: 's3', name: 'KPIs Principales', type: 'kpi', module: 'dashboard', enabled: true, order: 3 },
      { id: 's4', name: 'Resultados por Canal', type: 'chart', module: 'campaigns', enabled: true, order: 4 },
      { id: 's5', name: 'Leads y Calidad', type: 'table', module: 'leads', enabled: true, order: 5 },
      { id: 's6', name: 'Conclusiones', type: 'text', module: 'general', enabled: true, order: 6 },
    ],
    recipients: ['director@vertex.com', 'marketing@vertex.com'],
    lastSent: '2024-01-15',
    nextSend: '2024-02-15',
    status: 'programado',
    responsibleId: 'user-1',
    responsibleName: 'María García',
    includeAiComments: true,
    managerComments: 'Excelente performance en Meta Ads. Recomendamos incrementar presupuesto.',
    conclusions: 'El CPL se mantuvo dentro del objetivo. Se superó la meta de leads en un 15%.',
    nextSteps: '1. Optimizar audiencias de remarketing\n2. Lanzar nueva campaña de Google Ads\n3. Revisar creativos de bajo rendimiento',
    useAgencyBranding: true,
    includeClientLogo: true,
    useClientColors: false,
    createdAt: '2024-01-01',
    updatedAt: '2024-01-15',
  },
  {
    id: 'rpt-2',
    name: 'Reporte Semanal - TechStart',
    clientId: 'client-2',
    clientName: 'TechStart',
    brandId: 'brand-2',
    brandName: 'TechStart SaaS',
    templateId: 'tpl-2',
    templateName: 'Reporte Pauta Digital',
    frequency: 'semanal',
    sections: [
      { id: 's1', name: 'Portada', type: 'image', module: 'general', enabled: true, order: 1 },
      { id: 's2', name: 'KPIs de Campaña', type: 'kpi', module: 'campaigns', enabled: true, order: 2 },
      { id: 's3', name: 'Performance por Plataforma', type: 'chart', module: 'campaigns', enabled: true, order: 3 },
    ],
    recipients: ['ceo@techstart.com'],
    lastSent: '2024-01-22',
    nextSend: '2024-01-29',
    status: 'programado',
    responsibleId: 'user-2',
    responsibleName: 'Carlos López',
    includeAiComments: true,
    useAgencyBranding: true,
    includeClientLogo: true,
    useClientColors: true,
    createdAt: '2024-01-01',
    updatedAt: '2024-01-22',
  },
  {
    id: 'rpt-3',
    name: 'Reporte Redes Sociales - FoodDelight',
    clientId: 'client-3',
    clientName: 'FoodDelight',
    brandId: 'brand-3',
    brandName: 'FoodDelight Restaurant',
    templateId: 'tpl-3',
    templateName: 'Reporte Redes Sociales',
    frequency: 'quincenal',
    sections: [
      { id: 's1', name: 'Engagement General', type: 'kpi', module: 'social', enabled: true, order: 1 },
      { id: 's2', name: 'Mejores Posts', type: 'table', module: 'social', enabled: true, order: 2 },
    ],
    recipients: ['owner@fooddelight.com'],
    lastSent: '2024-01-10',
    nextSend: '2024-01-25',
    status: 'borrador',
    responsibleId: 'user-3',
    responsibleName: 'Ana Martínez',
    includeAiComments: false,
    useAgencyBranding: true,
    includeClientLogo: false,
    useClientColors: false,
    createdAt: '2024-01-05',
    updatedAt: '2024-01-10',
  },
]

// ==================== REPORT HISTORY ====================
export const mockReportHistory: ReportHistory[] = [
  {
    id: 'hist-1',
    reportId: 'rpt-1',
    reportName: 'Reporte Mensual - Vertex',
    clientName: 'Vertex Inmobiliaria',
    brandName: 'Torre Skyline',
    sentAt: '2024-01-15T10:30:00Z',
    recipients: ['director@vertex.com', 'marketing@vertex.com'],
    format: 'pdf',
    status: 'enviado',
    responsibleName: 'María García',
  },
  {
    id: 'hist-2',
    reportId: 'rpt-1',
    reportName: 'Reporte Mensual - Vertex',
    clientName: 'Vertex Inmobiliaria',
    brandName: 'Torre Skyline',
    sentAt: '2023-12-15T10:30:00Z',
    recipients: ['director@vertex.com', 'marketing@vertex.com'],
    format: 'pdf',
    status: 'enviado',
    responsibleName: 'María García',
  },
  {
    id: 'hist-3',
    reportId: 'rpt-2',
    reportName: 'Reporte Semanal - TechStart',
    clientName: 'TechStart',
    brandName: 'TechStart SaaS',
    sentAt: '2024-01-22T09:00:00Z',
    recipients: ['ceo@techstart.com'],
    format: 'excel',
    status: 'enviado',
    responsibleName: 'Carlos López',
  },
]

// ==================== AI INSIGHTS ====================
export const mockAiInsights: AiInsight[] = [
  {
    id: 'ins-1',
    type: 'anomaly',
    title: 'CPL incrementó significativamente',
    description: 'El CPL de Meta Ads aumentó 28% contra el periodo anterior, pasando de $45 a $58.',
    clientId: 'client-1',
    clientName: 'Vertex Inmobiliaria',
    brandId: 'brand-1',
    brandName: 'Torre Skyline',
    module: 'campaigns',
    priority: 'alta',
    metric: 'CPL',
    currentValue: 58,
    previousValue: 45,
    changePercent: 28,
    recommendation: 'Revisar segmentación de audiencias y optimizar creativos de bajo rendimiento.',
    createdAt: '2024-01-25T08:00:00Z',
    status: 'nuevo',
  },
  {
    id: 'ins-2',
    type: 'finding',
    title: 'Google Ads genera leads de mayor calidad',
    description: 'Los leads de Google Ads tienen un 35% más de probabilidad de conversión que Meta Ads.',
    clientId: 'client-1',
    clientName: 'Vertex Inmobiliaria',
    brandId: 'brand-1',
    brandName: 'Torre Skyline',
    module: 'leads',
    priority: 'media',
    recommendation: 'Considerar redistribuir presupuesto hacia Google Ads.',
    createdAt: '2024-01-24T14:00:00Z',
    status: 'revisado',
  },
  {
    id: 'ins-3',
    type: 'finding',
    title: 'Mejor horario para reels en Instagram',
    description: 'Los reels publicados entre 7:00 PM y 9:00 PM tienen 45% más engagement.',
    clientId: 'client-3',
    clientName: 'FoodDelight',
    brandId: 'brand-3',
    brandName: 'FoodDelight Restaurant',
    module: 'social',
    priority: 'baja',
    recommendation: 'Programar reels en horario nocturno.',
    createdAt: '2024-01-23T10:00:00Z',
    status: 'aplicado',
  },
  {
    id: 'ins-4',
    type: 'anomaly',
    title: 'Campaña de remarketing con frecuencia alta',
    description: 'La campaña de remarketing muestra frecuencia de 8.5, lo cual puede generar fatiga.',
    clientId: 'client-2',
    clientName: 'TechStart',
    brandId: 'brand-2',
    brandName: 'TechStart SaaS',
    module: 'campaigns',
    priority: 'alta',
    metric: 'Frequency',
    currentValue: 8.5,
    previousValue: 4.2,
    changePercent: 102,
    recommendation: 'Ampliar audiencia o reducir presupuesto de remarketing.',
    createdAt: '2024-01-25T11:00:00Z',
    status: 'nuevo',
  },
  {
    id: 'ins-5',
    type: 'anomaly',
    title: 'Caída de tráfico orgánico',
    description: 'El tráfico orgánico cayó 15% en la página principal del proyecto.',
    clientId: 'client-1',
    clientName: 'Vertex Inmobiliaria',
    brandId: 'brand-1',
    brandName: 'Torre Skyline',
    module: 'seo',
    priority: 'media',
    metric: 'Organic Traffic',
    currentValue: 8500,
    previousValue: 10000,
    changePercent: -15,
    recommendation: 'Revisar posiciones de keywords principales y optimizar contenido.',
    createdAt: '2024-01-24T09:00:00Z',
    status: 'nuevo',
  },
  {
    id: 'ins-6',
    type: 'recommendation',
    title: 'Oportunidad de optimización de CTR',
    description: 'Anuncios con CTR bajo tienen potencial de mejora con nuevos copies.',
    clientId: 'client-2',
    clientName: 'TechStart',
    brandId: 'brand-2',
    brandName: 'TechStart SaaS',
    module: 'campaigns',
    priority: 'media',
    recommendation: 'Realizar A/B testing con nuevos headlines.',
    createdAt: '2024-01-23T16:00:00Z',
    status: 'revisado',
  },
]

// ==================== AI TASKS ====================
export const mockAiTasks: AiTask[] = [
  {
    id: 'task-1',
    task: 'Revisar y optimizar audiencias de Meta Ads',
    clientId: 'client-1',
    clientName: 'Vertex Inmobiliaria',
    brandId: 'brand-1',
    brandName: 'Torre Skyline',
    priority: 'alta',
    suggestedResponsible: 'Carlos López',
    suggestedDate: '2024-01-28',
    status: 'pendiente',
    createdAt: '2024-01-25T08:00:00Z',
  },
  {
    id: 'task-2',
    task: 'Crear nuevos creativos para campaña de remarketing',
    clientId: 'client-2',
    clientName: 'TechStart',
    brandId: 'brand-2',
    brandName: 'TechStart SaaS',
    priority: 'alta',
    suggestedResponsible: 'Ana Martínez',
    suggestedDate: '2024-01-27',
    status: 'asignada',
    createdAt: '2024-01-25T11:00:00Z',
  },
  {
    id: 'task-3',
    task: 'Optimizar meta descriptions para SEO',
    clientId: 'client-1',
    clientName: 'Vertex Inmobiliaria',
    brandId: 'brand-1',
    brandName: 'Torre Skyline',
    priority: 'media',
    suggestedResponsible: 'María García',
    suggestedDate: '2024-01-30',
    status: 'pendiente',
    createdAt: '2024-01-24T09:00:00Z',
  },
  {
    id: 'task-4',
    task: 'Programar reels en horario óptimo',
    clientId: 'client-3',
    clientName: 'FoodDelight',
    brandId: 'brand-3',
    brandName: 'FoodDelight Restaurant',
    priority: 'baja',
    suggestedResponsible: 'Ana Martínez',
    suggestedDate: '2024-01-26',
    status: 'completada',
    createdAt: '2024-01-23T10:00:00Z',
  },
]

// ==================== ALERTS ====================
export const mockAlerts: Alert[] = [
  {
    id: 'alert-1',
    type: 'cpl_alto',
    title: 'CPL alto en Meta Ads',
    description: 'El CPL superó el umbral configurado de $50, actualmente en $58.',
    clientId: 'client-1',
    clientName: 'Vertex Inmobiliaria',
    brandId: 'brand-1',
    brandName: 'Torre Skyline',
    module: 'campaigns',
    priority: 'alta',
    status: 'nueva',
    suggestedAction: 'Revisar segmentación y creativos de la campaña.',
    createdAt: '2024-01-25T08:00:00Z',
    channels: ['sistema', 'email'],
  },
  {
    id: 'alert-2',
    type: 'token_expirado',
    title: 'Token de Instagram expirado',
    description: 'El token de acceso de Instagram para FoodDelight ha expirado.',
    clientId: 'client-3',
    clientName: 'FoodDelight',
    brandId: 'brand-3',
    brandName: 'FoodDelight Restaurant',
    module: 'connectors',
    priority: 'critica',
    status: 'nueva',
    suggestedAction: 'Reconectar la cuenta de Instagram.',
    createdAt: '2024-01-25T07:30:00Z',
    channels: ['sistema', 'email'],
  },
  {
    id: 'alert-3',
    type: 'reporte_pendiente',
    title: 'Reporte mensual pendiente',
    description: 'El reporte mensual de Vertex vence en 3 días.',
    clientId: 'client-1',
    clientName: 'Vertex Inmobiliaria',
    brandId: 'brand-1',
    brandName: 'Torre Skyline',
    module: 'reports',
    priority: 'media',
    status: 'en_revision',
    responsibleId: 'user-1',
    responsibleName: 'María García',
    suggestedAction: 'Completar y enviar el reporte.',
    createdAt: '2024-01-24T10:00:00Z',
    channels: ['sistema'],
  },
  {
    id: 'alert-4',
    type: 'comentario_negativo',
    title: 'Comentario negativo detectado',
    description: 'Se detectó un comentario negativo en Instagram que requiere respuesta.',
    clientId: 'client-3',
    clientName: 'FoodDelight',
    brandId: 'brand-3',
    brandName: 'FoodDelight Restaurant',
    module: 'inbox',
    priority: 'alta',
    status: 'asignada',
    responsibleId: 'user-3',
    responsibleName: 'Ana Martínez',
    suggestedAction: 'Responder al comentario de forma profesional.',
    createdAt: '2024-01-24T15:00:00Z',
    channels: ['sistema', 'email'],
  },
  {
    id: 'alert-5',
    type: 'frecuencia_alta',
    title: 'Frecuencia alta en remarketing',
    description: 'La campaña de remarketing tiene frecuencia de 8.5, superando el umbral de 6.',
    clientId: 'client-2',
    clientName: 'TechStart',
    brandId: 'brand-2',
    brandName: 'TechStart SaaS',
    module: 'campaigns',
    priority: 'media',
    status: 'nueva',
    suggestedAction: 'Ampliar audiencia o ajustar presupuesto.',
    createdAt: '2024-01-25T11:00:00Z',
    channels: ['sistema'],
  },
  {
    id: 'alert-6',
    type: 'keyword_perdida',
    title: 'Keyword importante perdió posiciones',
    description: 'La keyword "departamentos en venta" bajó de posición 3 a posición 8.',
    clientId: 'client-1',
    clientName: 'Vertex Inmobiliaria',
    brandId: 'brand-1',
    brandName: 'Torre Skyline',
    module: 'seo',
    priority: 'alta',
    status: 'nueva',
    suggestedAction: 'Revisar contenido y backlinks de la página.',
    createdAt: '2024-01-25T06:00:00Z',
    channels: ['sistema', 'email'],
  },
  {
    id: 'alert-7',
    type: 'sin_leads',
    title: 'Campaña sin leads en 3 días',
    description: 'La campaña "Leads Q1" no ha generado leads en los últimos 3 días.',
    clientId: 'client-2',
    clientName: 'TechStart',
    brandId: 'brand-2',
    brandName: 'TechStart SaaS',
    module: 'campaigns',
    priority: 'alta',
    status: 'resuelta',
    responsibleId: 'user-2',
    responsibleName: 'Carlos López',
    suggestedAction: 'Revisar configuración de la campaña.',
    createdAt: '2024-01-22T10:00:00Z',
    resolvedAt: '2024-01-23T14:00:00Z',
    channels: ['sistema'],
  },
]

// ==================== ALERT RULES ====================
export const mockAlertRules: AlertRule[] = [
  {
    id: 'rule-1',
    name: 'CPL alto',
    type: 'cpl_alto',
    condition: 'CPL > threshold',
    threshold: 50,
    priority: 'alta',
    channels: ['sistema', 'email'],
    enabled: true,
  },
  {
    id: 'rule-2',
    name: 'CTR bajo',
    type: 'ctr_bajo',
    condition: 'CTR < threshold',
    threshold: 1,
    priority: 'media',
    channels: ['sistema'],
    enabled: true,
  },
  {
    id: 'rule-3',
    name: 'Sin leads en 3 días',
    type: 'sin_leads',
    condition: 'leads_3_days == 0',
    threshold: 0,
    priority: 'alta',
    channels: ['sistema', 'email'],
    enabled: true,
  },
  {
    id: 'rule-4',
    name: 'Token expirado',
    type: 'token_expirado',
    condition: 'token_status == expired',
    threshold: 0,
    priority: 'critica',
    channels: ['sistema', 'email'],
    enabled: true,
  },
  {
    id: 'rule-5',
    name: 'Frecuencia alta',
    type: 'frecuencia_alta',
    condition: 'frequency > threshold',
    threshold: 6,
    priority: 'media',
    channels: ['sistema'],
    enabled: true,
  },
  {
    id: 'rule-6',
    name: 'Keyword perdió posiciones',
    type: 'keyword_perdida',
    condition: 'position_drop > threshold',
    threshold: 5,
    priority: 'alta',
    channels: ['sistema', 'email'],
    enabled: true,
  },
]

// ==================== USERS ====================
export const mockUsers: User[] = [
  {
    id: 'user-1',
    name: 'María García',
    email: 'maria@agencia.com',
    avatar: '',
    role: 'director',
    assignedClients: ['client-1', 'client-2', 'client-3'],
    assignedBrands: ['brand-1', 'brand-2', 'brand-3'],
    status: 'activo',
    lastAccess: '2024-01-25T10:30:00Z',
    createdAt: '2023-01-01',
  },
  {
    id: 'user-2',
    name: 'Carlos López',
    email: 'carlos@agencia.com',
    avatar: '',
    role: 'account_manager',
    assignedClients: ['client-1', 'client-2'],
    assignedBrands: ['brand-1', 'brand-2'],
    status: 'activo',
    lastAccess: '2024-01-25T09:15:00Z',
    createdAt: '2023-03-15',
  },
  {
    id: 'user-3',
    name: 'Ana Martínez',
    email: 'ana@agencia.com',
    avatar: '',
    role: 'community_manager',
    assignedClients: ['client-3'],
    assignedBrands: ['brand-3'],
    status: 'activo',
    lastAccess: '2024-01-25T08:45:00Z',
    createdAt: '2023-06-01',
  },
  {
    id: 'user-4',
    name: 'Pedro Sánchez',
    email: 'pedro@agencia.com',
    avatar: '',
    role: 'analista',
    assignedClients: ['client-1', 'client-2'],
    assignedBrands: ['brand-1', 'brand-2'],
    status: 'activo',
    lastAccess: '2024-01-24T18:00:00Z',
    createdAt: '2023-08-01',
  },
  {
    id: 'user-5',
    name: 'Laura Fernández',
    email: 'laura@agencia.com',
    avatar: '',
    role: 'disenador',
    assignedClients: ['client-1', 'client-2', 'client-3'],
    assignedBrands: ['brand-1', 'brand-2', 'brand-3'],
    status: 'activo',
    lastAccess: '2024-01-25T07:30:00Z',
    createdAt: '2023-09-15',
  },
  {
    id: 'user-6',
    name: 'Roberto Vertex',
    email: 'roberto@vertex.com',
    avatar: '',
    role: 'cliente',
    assignedClients: ['client-1'],
    assignedBrands: ['brand-1'],
    status: 'activo',
    lastAccess: '2024-01-20T14:00:00Z',
    createdAt: '2023-10-01',
  },
]

// ==================== ROLE PERMISSIONS ====================
export const mockRolePermissions: RolePermissions[] = [
  {
    role: 'director',
    roleName: 'Director',
    description: 'Acceso completo a todos los módulos y funcionalidades',
    permissions: [
      {
        moduleId: 'dashboard',
        moduleName: 'Dashboard',
        actions: [
          { action: 'ver', allowed: true },
          { action: 'crear', allowed: true },
          { action: 'editar', allowed: true },
          { action: 'eliminar', allowed: true },
          { action: 'exportar', allowed: true },
        ],
      },
      {
        moduleId: 'campaigns',
        moduleName: 'Campañas',
        actions: [
          { action: 'ver', allowed: true },
          { action: 'crear', allowed: true },
          { action: 'editar', allowed: true },
          { action: 'eliminar', allowed: true },
          { action: 'exportar', allowed: true },
        ],
      },
      {
        moduleId: 'users',
        moduleName: 'Usuarios',
        actions: [
          { action: 'ver', allowed: true },
          { action: 'crear', allowed: true },
          { action: 'editar', allowed: true },
          { action: 'eliminar', allowed: true },
          { action: 'admin_usuarios', allowed: true },
        ],
      },
    ],
  },
  {
    role: 'account_manager',
    roleName: 'Account Manager',
    description: 'Gestión de clientes y reportes',
    permissions: [
      {
        moduleId: 'dashboard',
        moduleName: 'Dashboard',
        actions: [
          { action: 'ver', allowed: true },
          { action: 'crear', allowed: true },
          { action: 'editar', allowed: true },
          { action: 'eliminar', allowed: false },
          { action: 'exportar', allowed: true },
        ],
      },
      {
        moduleId: 'reports',
        moduleName: 'Reportes',
        actions: [
          { action: 'ver', allowed: true },
          { action: 'crear', allowed: true },
          { action: 'editar', allowed: true },
          { action: 'comentar', allowed: true },
          { action: 'exportar', allowed: true },
          { action: 'config_reportes', allowed: true },
        ],
      },
    ],
  },
  {
    role: 'analista',
    roleName: 'Analista',
    description: 'Visualización y análisis de datos',
    permissions: [
      {
        moduleId: 'dashboard',
        moduleName: 'Dashboard',
        actions: [
          { action: 'ver', allowed: true },
          { action: 'ver_metricas', allowed: true },
          { action: 'exportar', allowed: true },
        ],
      },
      {
        moduleId: 'connectors',
        moduleName: 'Conectores',
        actions: [
          { action: 'ver', allowed: true },
          { action: 'conectar_cuentas', allowed: true },
        ],
      },
    ],
  },
  {
    role: 'community_manager',
    roleName: 'Community Manager',
    description: 'Gestión de contenido y redes sociales',
    permissions: [
      {
        moduleId: 'social',
        moduleName: 'Redes Sociales',
        actions: [
          { action: 'ver', allowed: true },
          { action: 'crear', allowed: true },
          { action: 'editar', allowed: true },
          { action: 'programar', allowed: true },
          { action: 'publicar', allowed: true },
        ],
      },
      {
        moduleId: 'inbox',
        moduleName: 'Inbox',
        actions: [
          { action: 'ver', allowed: true },
          { action: 'responder_inbox', allowed: true },
        ],
      },
      {
        moduleId: 'calendar',
        moduleName: 'Calendario',
        actions: [
          { action: 'ver', allowed: true },
          { action: 'crear', allowed: true },
          { action: 'editar', allowed: true },
        ],
      },
    ],
  },
  {
    role: 'disenador',
    roleName: 'Diseñador',
    description: 'Visualización de calendario y subida de creativos',
    permissions: [
      {
        moduleId: 'calendar',
        moduleName: 'Calendario',
        actions: [
          { action: 'ver', allowed: true },
        ],
      },
      {
        moduleId: 'social',
        moduleName: 'Redes Sociales',
        actions: [
          { action: 'ver', allowed: true },
          { action: 'crear', allowed: true },
        ],
      },
    ],
  },
  {
    role: 'cliente',
    roleName: 'Cliente',
    description: 'Visualización de dashboards y aprobación de contenido',
    permissions: [
      {
        moduleId: 'dashboard',
        moduleName: 'Dashboard',
        actions: [
          { action: 'ver', allowed: true },
          { action: 'ver_metricas', allowed: true },
        ],
      },
      {
        moduleId: 'reports',
        moduleName: 'Reportes',
        actions: [
          { action: 'ver', allowed: true },
          { action: 'ver_reportes', allowed: true },
        ],
      },
      {
        moduleId: 'approvals',
        moduleName: 'Aprobaciones',
        actions: [
          { action: 'ver', allowed: true },
          { action: 'aprobar', allowed: true },
          { action: 'comentar', allowed: true },
        ],
      },
    ],
  },
  {
    role: 'solo_lectura',
    roleName: 'Solo Lectura',
    description: 'Acceso de solo visualización',
    permissions: [
      {
        moduleId: 'dashboard',
        moduleName: 'Dashboard',
        actions: [
          { action: 'ver', allowed: true },
        ],
      },
      {
        moduleId: 'reports',
        moduleName: 'Reportes',
        actions: [
          { action: 'ver', allowed: true },
        ],
      },
    ],
  },
]

// ==================== AUDIT LOGS ====================
export const mockAuditLogs: AuditLog[] = [
  {
    id: 'log-1',
    userId: 'user-1',
    userName: 'María García',
    userEmail: 'maria@agencia.com',
    action: 'enviar_reporte',
    actionLabel: 'Enviar reporte',
    module: 'Reportes',
    clientId: 'client-1',
    clientName: 'Vertex Inmobiliaria',
    brandId: 'brand-1',
    brandName: 'Torre Skyline',
    recordId: 'rpt-1',
    recordType: 'report',
    ip: '192.168.1.100',
    device: 'Desktop',
    browser: 'Chrome 120',
    timestamp: '2024-01-25T10:30:00Z',
  },
  {
    id: 'log-2',
    userId: 'user-2',
    userName: 'Carlos López',
    userEmail: 'carlos@agencia.com',
    action: 'conexion_cuenta',
    actionLabel: 'Conectar cuenta',
    module: 'Conectores',
    clientId: 'client-2',
    clientName: 'TechStart',
    brandId: 'brand-2',
    brandName: 'TechStart SaaS',
    recordId: 'conn-5',
    recordType: 'connector',
    newValue: 'Google Ads conectado',
    ip: '192.168.1.101',
    device: 'Desktop',
    browser: 'Firefox 122',
    timestamp: '2024-01-25T09:15:00Z',
  },
  {
    id: 'log-3',
    userId: 'user-3',
    userName: 'Ana Martínez',
    userEmail: 'ana@agencia.com',
    action: 'aprobar_post',
    actionLabel: 'Aprobar publicación',
    module: 'Aprobaciones',
    clientId: 'client-3',
    clientName: 'FoodDelight',
    brandId: 'brand-3',
    brandName: 'FoodDelight Restaurant',
    recordId: 'post-15',
    recordType: 'post',
    previousValue: 'pendiente',
    newValue: 'aprobado',
    ip: '192.168.1.102',
    device: 'Mobile',
    browser: 'Safari 17',
    timestamp: '2024-01-25T08:45:00Z',
  },
  {
    id: 'log-4',
    userId: 'user-1',
    userName: 'María García',
    userEmail: 'maria@agencia.com',
    action: 'cambiar_permisos',
    actionLabel: 'Cambiar permisos',
    module: 'Usuarios',
    recordId: 'user-4',
    recordType: 'user',
    previousValue: 'analista',
    newValue: 'account_manager',
    ip: '192.168.1.100',
    device: 'Desktop',
    browser: 'Chrome 120',
    timestamp: '2024-01-24T16:00:00Z',
  },
  {
    id: 'log-5',
    userId: 'user-2',
    userName: 'Carlos López',
    userEmail: 'carlos@agencia.com',
    action: 'generar_insight',
    actionLabel: 'Generar insight IA',
    module: 'IA e Insights',
    clientId: 'client-1',
    clientName: 'Vertex Inmobiliaria',
    brandId: 'brand-1',
    brandName: 'Torre Skyline',
    recordId: 'ins-1',
    recordType: 'insight',
    ip: '192.168.1.101',
    device: 'Desktop',
    browser: 'Firefox 122',
    timestamp: '2024-01-24T14:30:00Z',
  },
  {
    id: 'log-6',
    userId: 'user-3',
    userName: 'Ana Martínez',
    userEmail: 'ana@agencia.com',
    action: 'responder_inbox',
    actionLabel: 'Responder mensaje',
    module: 'Inbox',
    clientId: 'client-3',
    clientName: 'FoodDelight',
    brandId: 'brand-3',
    brandName: 'FoodDelight Restaurant',
    recordId: 'msg-25',
    recordType: 'message',
    ip: '192.168.1.102',
    device: 'Mobile',
    browser: 'Safari 17',
    timestamp: '2024-01-24T11:00:00Z',
  },
  {
    id: 'log-7',
    userId: 'user-1',
    userName: 'María García',
    userEmail: 'maria@agencia.com',
    action: 'exportar_datos',
    actionLabel: 'Exportar datos',
    module: 'Data Warehouse',
    clientId: 'client-1',
    clientName: 'Vertex Inmobiliaria',
    newValue: 'Exportación CSV - 1,250 registros',
    ip: '192.168.1.100',
    device: 'Desktop',
    browser: 'Chrome 120',
    timestamp: '2024-01-23T17:00:00Z',
  },
  {
    id: 'log-8',
    userId: 'user-4',
    userName: 'Pedro Sánchez',
    userEmail: 'pedro@agencia.com',
    action: 'crear_dashboard',
    actionLabel: 'Crear dashboard',
    module: 'Dashboards',
    clientId: 'client-2',
    clientName: 'TechStart',
    brandId: 'brand-2',
    brandName: 'TechStart SaaS',
    recordId: 'dash-8',
    recordType: 'dashboard',
    newValue: 'Dashboard Q1 2024',
    ip: '192.168.1.103',
    device: 'Desktop',
    browser: 'Chrome 120',
    timestamp: '2024-01-23T10:00:00Z',
  },
]

// ==================== SETTINGS ====================
export const mockSettings: Settings = {
  general: {
    moduleName: 'Orbit Marketing Intelligence',
    primaryColor: '#6366f1',
    secondaryColor: '#8b5cf6',
    darkMode: false,
    timezone: 'America/Mexico_City',
    currency: 'MXN',
    language: 'es',
  },
  branding: {
    agencyName: 'A4R Marketing Digital',
    agencyColors: {
      primary: '#6366f1',
      secondary: '#8b5cf6',
      accent: '#ec4899',
    },
    reportFooter: '© 2024 A4R Marketing Digital. Todos los derechos reservados.',
    emailSignature: 'Equipo A4R Marketing Digital',
  },
  connectors: {
    autoSync: true,
    syncFrequency: 'daily',
    retryAttempts: 3,
    notifyOnError: true,
  },
  ai: {
    provider: 'chatgpt',
    model: 'gpt-4',
    autoGenerateInsights: true,
    insightFrequency: 'daily',
    contentSuggestions: true,
    anomalyDetection: true,
  },
  alerts: {
    emailNotifications: true,
    inAppNotifications: true,
    digestFrequency: 'daily',
    defaultPriority: 'media',
    thresholds: {
      cplIncrease: 20,
      ctrDecrease: 1,
      roasDecrease: 20,
      keywordPositionDrop: 5,
      competitorGrowth: 15,
    },
  },
}

// ==================== DATA BLENDS ====================
export const mockDataBlends: DataBlend[] = [
  {
    id: 'blend-1',
    name: 'Meta Ads + CRM',
    description: 'Combina datos de campañas de Meta con leads del CRM',
    sources: [
      { sourceId: 'meta-ads', sourceName: 'Meta Ads', fields: ['campaign_id', 'spend', 'clicks', 'leads'] },
      { sourceId: 'crm', sourceName: 'HubSpot CRM', fields: ['lead_id', 'source', 'status', 'value'] },
    ],
    joinKey: 'utm_campaign',
    outputFields: ['campaign_name', 'spend', 'leads', 'qualified_leads', 'cpl', 'cpa'],
    status: 'activo',
    lastSync: '2024-01-25T06:00:00Z',
  },
  {
    id: 'blend-2',
    name: 'Google Ads + CRM',
    description: 'Combina datos de Google Ads con conversiones del CRM',
    sources: [
      { sourceId: 'google-ads', sourceName: 'Google Ads', fields: ['campaign_id', 'spend', 'clicks', 'conversions'] },
      { sourceId: 'crm', sourceName: 'HubSpot CRM', fields: ['lead_id', 'source', 'status', 'value'] },
    ],
    joinKey: 'gclid',
    outputFields: ['campaign_name', 'spend', 'conversions', 'revenue', 'roas'],
    status: 'activo',
    lastSync: '2024-01-25T06:00:00Z',
  },
  {
    id: 'blend-3',
    name: 'GA4 + Search Console',
    description: 'Combina tráfico orgánico con datos de búsqueda',
    sources: [
      { sourceId: 'ga4', sourceName: 'Google Analytics 4', fields: ['page', 'sessions', 'users', 'bounceRate'] },
      { sourceId: 'gsc', sourceName: 'Search Console', fields: ['query', 'clicks', 'impressions', 'position'] },
    ],
    joinKey: 'landing_page',
    outputFields: ['page', 'organic_sessions', 'top_queries', 'avg_position', 'ctr'],
    status: 'activo',
    lastSync: '2024-01-25T06:00:00Z',
  },
  {
    id: 'blend-4',
    name: 'Redes Sociales + Calendario',
    description: 'Combina métricas de posts con programación',
    sources: [
      { sourceId: 'social', sourceName: 'Redes Sociales', fields: ['post_id', 'likes', 'comments', 'shares', 'reach'] },
      { sourceId: 'calendar', sourceName: 'Calendario', fields: ['post_id', 'scheduled_date', 'type', 'platform'] },
    ],
    joinKey: 'post_id',
    outputFields: ['post_type', 'platform', 'engagement_rate', 'best_time', 'reach'],
    status: 'activo',
    lastSync: '2024-01-25T06:00:00Z',
  },
]

// ==================== DATA DESTINATIONS ====================
export const mockDataDestinations: DataDestinationConfig[] = [
  {
    id: 'dest-1',
    type: 'supabase',
    name: 'Supabase Principal',
    config: { project: 'orbit-mi', region: 'us-east-1' },
    tables: ['metrics', 'campaigns', 'leads', 'posts'],
    status: 'conectado',
    lastSync: '2024-01-25T06:00:00Z',
  },
  {
    id: 'dest-2',
    type: 'google_sheets',
    name: 'Google Sheets - Reportes',
    config: { spreadsheetId: '1abc...xyz' },
    tables: ['weekly_summary', 'monthly_kpis'],
    status: 'conectado',
    lastSync: '2024-01-25T06:00:00Z',
  },
  {
    id: 'dest-3',
    type: 'looker_studio',
    name: 'Looker Studio - Dashboard Cliente',
    config: { dataSourceId: 'ds_123' },
    tables: ['client_dashboard_data'],
    status: 'conectado',
    lastSync: '2024-01-24T18:00:00Z',
  },
]

// ==================== SYNC LOGS ====================
export const mockSyncLogs: SyncLog[] = [
  {
    id: 'sync-1',
    connectorId: 'conn-1',
    connectorName: 'Meta Ads - Vertex',
    startTime: '2024-01-25T06:00:00Z',
    endTime: '2024-01-25T06:05:32Z',
    status: 'completado',
    recordsProcessed: 1250,
    recordsFailed: 0,
  },
  {
    id: 'sync-2',
    connectorId: 'conn-2',
    connectorName: 'Google Ads - TechStart',
    startTime: '2024-01-25T06:00:00Z',
    endTime: '2024-01-25T06:03:15Z',
    status: 'completado',
    recordsProcessed: 890,
    recordsFailed: 2,
    errorMessage: '2 registros con fecha inválida',
  },
  {
    id: 'sync-3',
    connectorId: 'conn-3',
    connectorName: 'Instagram - FoodDelight',
    startTime: '2024-01-25T06:00:00Z',
    status: 'error',
    recordsProcessed: 0,
    recordsFailed: 0,
    errorMessage: 'Token de acceso expirado',
  },
  {
    id: 'sync-4',
    connectorId: 'conn-1',
    connectorName: 'Meta Ads - Vertex',
    startTime: '2024-01-24T06:00:00Z',
    endTime: '2024-01-24T06:04:45Z',
    status: 'completado',
    recordsProcessed: 1180,
    recordsFailed: 0,
  },
]

// ==================== CUSTOM CONNECTORS ====================
export const mockCustomConnectors: CustomConnector[] = [
  {
    id: 'custom-1',
    name: 'API Inmobiliaria',
    category: 'CRM',
    baseUrl: 'https://api.inmobiliaria.com',
    endpoint: '/v1/leads',
    method: 'GET',
    headers: { 'Content-Type': 'application/json' },
    params: { limit: '100', status: 'active' },
    authType: 'api_key',
    syncFrequency: 'daily',
    fieldMappings: [
      { id: 'fm-1', sourceField: 'id', sourceType: 'string', targetField: 'lead_id', targetType: 'string', isRequired: true },
      { id: 'fm-2', sourceField: 'nombre', sourceType: 'string', targetField: 'name', targetType: 'string', isRequired: true },
      { id: 'fm-3', sourceField: 'email', sourceType: 'string', targetField: 'email', targetType: 'string', isRequired: true },
      { id: 'fm-4', sourceField: 'telefono', sourceType: 'string', targetField: 'phone', targetType: 'string', isRequired: false },
    ],
    status: 'activo',
    lastTest: '2024-01-25T10:00:00Z',
    lastTestStatus: 'success',
    createdAt: '2024-01-15',
  },
  {
    id: 'custom-2',
    name: 'Webhook Ventas',
    category: 'Ventas',
    baseUrl: 'https://ventas.empresa.com',
    endpoint: '/api/conversions',
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    params: {},
    authType: 'bearer',
    syncFrequency: 'hourly',
    fieldMappings: [
      { id: 'fm-5', sourceField: 'conversion_id', sourceType: 'string', targetField: 'sale_id', targetType: 'string', isRequired: true },
      { id: 'fm-6', sourceField: 'amount', sourceType: 'number', targetField: 'value', targetType: 'number', isRequired: true },
    ],
    status: 'activo',
    lastTest: '2024-01-24T15:00:00Z',
    lastTestStatus: 'success',
    createdAt: '2024-01-10',
  },
]
